var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){a!=Array.prototype&&a!=Object.prototype&&(a[c]=b.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,c,b,d){if(c){b=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in b||(b[e]={});b=b[e]}a=a[a.length-1];d=b[a];c=c(d);c!=d&&null!=c&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:c})}};$jscomp.polyfill("Object.is",function(a){return a?a:function(a,b){return a===b?0!==a||1/a===1/b:a!==a&&b!==b}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(a,b){var c=this;c instanceof String&&(c=String(c));var e=c.length;b=b||0;for(0>b&&(b=Math.max(b+e,0));b<e;b++){var f=c[b];if(f===a||Object.is(f,a))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,c,b){if(null==a)throw new TypeError("The 'this' value for String.prototype."+b+" must not be null or undefined");if(c instanceof RegExp)throw new TypeError("First argument to String.prototype."+b+" must not be a regular expression");return a+""};$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(a,b){return-1!==$jscomp.checkStringArgs(this,a,"includes").indexOf(a,b||0)}},"es6","es3");
var gGameConfig={sqGameFolderName:{},metrics:{url_get:"https://zjv2091mlf.execute-api.eu-west-1.amazonaws.com/production/get",url_save_unload:"https://yhe8ze7018.execute-api.eu-west-1.amazonaws.com/production/save",excludedOps:[]},operators:[{id:"555",name:"betsson"},{id:"581",name:"betsson"},{id:"196",name:"betsson"},{id:"674",name:"betsson"},{id:"512",name:"betsson"},{id:"104",name:"betsson"},{id:"423",name:"betsson"},{id:"675",name:"betsson"},{id:"623",name:"betsson"},{id:"213",name:"betsson"},
{id:"673",name:"betsson"},{id:"113",name:"mrgreen"},{id:"924",name:"mrgreen"},{id:"620",name:"mrgreen"},{id:"176",name:"leovegas"},{id:"990",name:"leovegas"},{id:"653",name:"leovegas"},{id:"431",name:"sisal"},{id:"668",name:"comeon"},{id:"682",name:"folkeautomaten"},{id:"683",name:"mobilebet"},{id:"687",name:"mobilautomaten"},{id:"681",name:"suomikasino"},{id:"686",name:"getlucky"},{id:"830",name:"norgesspill"},{id:"831",name:"norgesspill"},{id:"800",name:"cherrycasino"},{id:"829",name:"eurolotto"},
{id:"828",name:"euroslots"},{id:"834",name:"sveacasino"},{id:"832",name:"sunnyplayer"},{id:"812",name:"sunmaker"},{id:"684",name:"casinostugan"},{id:"999",name:"hajper"},{id:"998",name:"nopeampi"},{id:"997",name:"snabbare"},{id:"971",name:"frankandfredcasino"}],gameGroups:{thirdparty:[{gamename:"1leftalive",provider:"4theplayer"},{gamename:"bonanza",provider:"bigtimegaming"},{gamename:"starquest",provider:"bigtimegaming"},{gamename:"templequestspinfinity",provider:"bigtimegaming"},{gamename:"whiterabbit",
provider:"bigtimegaming"},{gamename:"dangerhighvoltage",provider:"bigtimegaming"},{gamename:"bookofgods",provider:"bigtimegaming"},{gamename:"donuts",provider:"bigtimegaming"},{gamename:"extrachilli",provider:"bigtimegaming"},{gamename:"queenofriches",provider:"bigtimegaming"},{gamename:"gold",provider:"bigtimegaming"},{gamename:"dragonborn",provider:"bigtimegaming"},{gamename:"starquest",provider:"bigtimegaming"},{gamename:"millionaire96",provider:"bigtimegaming"},{gamename:"opalfruits",provider:"bigtimegaming"},
{gamename:"holydiver",provider:"bigtimegaming"},{gamename:"kingmaker96",provider:"bigtimegaming"},{gamename:"lildevil96",provider:"bigtimegaming"},{gamename:"millionairemysterybox96",provider:"bigtimegaming",gambleCount:5},{gamename:"monopolymegaways96",provider:"bigtimegaming"},{gamename:"starclusters96",provider:"bigtimegaming"},{gamename:"royalmint96",provider:"bigtimegaming"},{gamename:"survivor96",provider:"bigtimegaming"},{gamename:"bountyhunt",provider:"chanceinteractive"},{gamename:"roguetreasure",
provider:"chanceinteractive"},{gamename:"busterhammer",provider:"chanceinteractive"},{gamename:"busterhammercarnival",provider:"chanceinteractive"},{gamename:"creepycastle",provider:"chanceinteractive"},{gamename:"lollyland",provider:"chanceinteractive"},{gamename:"furnace",provider:"coregaming"},{gamename:"grabbaslot",provider:"coregaming"},{gamename:"pathwaytoriches",provider:"coregaming"},{gamename:"wildcorral",provider:"coregaming"},{gamename:"olivertwist",provider:"Endmole"},{gamename:"doubleballroulette",
provider:"feltgaming"},{gamename:"blackjackvariants",provider:"feltgaming"},{gamename:"blackjack-perfect-pairs",provider:"feltgaming"},{gamename:"blackjack-suit-em-up",provider:"feltgaming"},{gamename:"blackjack-lucky-ladies",provider:"feltgaming"},{gamename:"blackjack-lucky-lucky",provider:"feltgaming"},{gamename:"blackjack-buster",provider:"feltgaming"},{gamename:"blackjack-twentyone-three",provider:"feltgaming"},{gamename:"fruitz",provider:"foxium"},{gamename:"luckybakery",provider:"foxium"},{gamename:"oddforest96",
provider:"foxium"},{gamename:"thelostrichesofamazon",provider:"foxium"},{gamename:"catburglar",provider:"gameslab"},{gamename:"jewelofthejungle",provider:"gameslab"},{gamename:"osiris",provider:"gameslab"},{gamename:"tianlong",provider:"gameslab"},{gamename:"crazypop",provider:"gameslab"},{gamename:"lightninghorseman",provider:"lightningbox"},{gamename:"silverlion",provider:"lightningbox"},{gamename:"mildrockers",provider:"lightningbox"},{gamename:"fivepirates",provider:"lightningbox"},{gamename:"dolphingold",
provider:"lightningbox"},{gamename:"dolphingoldhq",provider:"lightningbox"},{gamename:"vikingfire",provider:"lightningbox"},{gamename:"blazinggoddess",provider:"lightningbox"},{gamename:"pixiegold",provider:"lightningbox"},{gamename:"dragonpalace",provider:"lightningbox"},{gamename:"serengetilions",provider:"lightningbox"},{gamename:"astrocat",provider:"lightningbox"},{gamename:"astrocatdeluxe",provider:"lightningbox"},{gamename:"chilligold2",provider:"lightningbox"},{gamename:"redroo",provider:"lightningbox"},
{gamename:"dolphingoldjackpot",provider:"lightningbox"},{gamename:"respinrhino",provider:"lightningbox"},{gamename:"pandapow",provider:"lightningbox"},{gamename:"moremonkeysjackpot",provider:"lightningbox"},{gamename:"chickenfox",provider:"lightningbox"},{gamename:"pinatabucks",provider:"lightningbox"},{gamename:"blownaway",provider:"lightningbox"},{gamename:"eaglesun",provider:"lightningbox"},{gamename:"spartanfire",provider:"lightningbox"},{gamename:"billygonewild",provider:"live5"},{gamename:"bjornthefrostlord",
provider:"live5"},{gamename:"hercules",provider:"live5"},{gamename:"rocoloco",provider:"live5"},{gamename:"onehundredfortunes",provider:"northernlightsgaming"},{gamename:"luckybaccaratsqueezeblackjack",provider:"pixiugaming"},{gamename:"bigprizebubblegum",provider:"incredibletech"},{gamename:"misskitty",provider:"aristocrat"},{gamename:"redbaron",provider:"aristocrat"},{gamename:"choysundoa",provider:"aristocrat"},{gamename:"bigben",provider:"aristocrat"},{gamename:"50dragons",provider:"aristocrat"},
{gamename:"bigbucksbanditsmegaways",provider:"reelplay"},{gamename:"neopolis",provider:"r.franco"},{gamename:"wildcatcher",provider:"wildstreakgaming"},{gamename:"piggybankpayout",provider:"1x2gaming"},{gamename:"3handblackjack",provider:"hungrybear"}],sgdigital:[{gamename:"",provider:"sgdigital"}]}},launchTimeStamp=Date.now(),messageIndex=0,freeplay=!0,tracking=!0,latestData="";function lookupOperatorConfig(a,c){return configHelper.lookupOperatorConfig(a,c)}
function getFolderName(a,c){var b="";if(2<c.length&&-1==c.indexOf("lightninggems")&&-1==c.indexOf("lucky88")&&-1==c.indexOf("oddforest96")){var d=parseInt(c.slice(-2));80<=d&&99>=d&&(b=c.slice(0,-2))}""==b&&(b=c);"undefined"!==typeof gGameConfig.sqGameFolderName[c]&&"sq"==a&&(b=gGameConfig.sqGameFolderName[c]);return b}
function getGameProvider(a){var c="sgdigital";if(0<gGameConfig.gameGroups.thirdparty.length)for(var b=0;b<gGameConfig.gameGroups.thirdparty.length;b++)if(gGameConfig.gameGroups.thirdparty[b].gamename==a){c=gGameConfig.gameGroups.thirdparty[b].provider;break}return c}function getGameDefaultGambleCount(a){return configHelper.getGameDefaultGambleCount(a)}
function sendMetricsData(a){if(""!=a.trim()&&""!=gGameConfig.metrics.url_save_unload&&!(-1<urlParameters.serverAddress.indexOf("stage"))&&!0===tracking){var c=urlParameters.token.trim(),b=urlParameters.mode;if(!0===freeplay||"real"===b)""!=c&&(a=c+"-"+a),messageIndex++,latestData=launchTimeStamp+"#"+messageIndex+"#"+a}}
function postData_unload(){if(""!=latestData){msg=gGameConfig.metrics.url_save_unload+"?timestamp="+Date.now();var a=JSON.stringify({stat:latestData});$.ajax({url:msg,type:"POST",timeout:3E4,async:!1,data:a,headers:{"Content-Type":"application/json"},success:function(a){},error:function(a,b,d){}})}}
function getInitMetricsSettings(){if(""!=gGameConfig.metrics.url_get){msg=gGameConfig.metrics.url_get+"?timestamp="+Date.now();var a=JSON.stringify({gameid:urlParameters.gameName,opid:opid});$.ajax({url:msg,type:"POST",timeout:3E4,data:a,headers:{"Content-Type":"application/json"},success:function(a){freeplay=a.freeplay;tracking=a.tracking},error:function(a,b,d){}})}}
function handlePageUnload(){if(!0===tracking){var a=urlParameters.mode;if(!0===freeplay||"real"===a)return postData_unload(),null}}var iosDevice=/iphone|ipad|ipod/i.test(navigator.userAgent.toLowerCase()),iosUnloadTimer=[6E4,12E4,18E4,24E4],currentTimerIndex=0;function handleiOSPageUnload(){setTimeout(function(){handlePageUnload();currentTimerIndex<iosUnloadTimer.length-1&&currentTimerIndex++;handleiOSPageUnload()},iosUnloadTimer[currentTimerIndex])}
iosDevice?(handleiOSPageUnload(),window.addEventListener("pagehide",handlePageUnload)):window.addEventListener("beforeunload",function(a){handlePageUnload()});var gamesNormalScaledOniOS=["1leftalive"];function isGameHalfScaled(a){return!(!navigator.userAgent.match(/iPhone/i)||gamesNormalScaledOniOS.includes(a))}
"undefined"!==typeof exports&&(module.exports={getGameProvider:getGameProvider,lookupOperatorConfig:lookupOperatorConfig,isGameHalfScaled:isGameHalfScaled,getGameDefaultGambleCount:getGameDefaultGambleCount,gGameConfig:gGameConfig});
/* Version 3.0.17 Date: 20200514 */
