function RealityCheck(h){var q=!1,g=ogsParams.realitycheck_uk_limit?ogsParams.realitycheck_uk_limit:gup("realitycheck_uk_limit");g=""==g?0:Number(g);var n=ogsParams.realitycheck_uk_elapsed?Number(ogsParams.realitycheck_uk_elapsed):Number(gup("realitycheck_uk_elapsed")),u=ogsParams.realitycheck_uk_proceed?decodeURIComponent(ogsParams.realitycheck_uk_proceed):decodeURIComponent(gup("realitycheck_uk_proceed")),v=ogsParams.realitycheck_uk_exit?decodeURIComponent(ogsParams.realitycheck_uk_exit):decodeURIComponent(gup("realitycheck_uk_exit")),
z=ogsParams.realitycheck_uk_history?decodeURIComponent(ogsParams.realitycheck_uk_history):decodeURIComponent(gup("realitycheck_uk_history")),A=ogsParams.realitycheck_uk_autospin?decodeURIComponent(ogsParams.realitycheck_uk_autospin):decodeURIComponent(gup("realitycheck_uk_autospin")),m=0,r=ogsParams.realitycheck_uk_timestamp?ogsParams.realitycheck_uk_timestamp:gup("realitycheck_uk_timestamp");r=0==r.length?0:Number(r);var p=0,e=n<g?g:g+n,w=!1;this.RC_ACTION_TEXT=["PROCEED","EXIT","HISTORY","AUTOPLAY"];
this.RC_NOTIFICATION_LINK=[u,v,z,A];var t=[wrappertexts.language[h].reality_check_proceed,wrappertexts.language[h].reality_check_exit,wrappertexts.language[h].reality_check_history];w="uk"==urlParameters.jurisdiction&&0<g?!0:!1;var c=this,l=null,B=["929"];this.getPlayedTime=function(){return e};this.startLocalTimer=function(){null!=l&&(clearTimeout(l),l=null);0<m?(m<=p&&(p=0),l=setTimeout(function(){inGameRound||c.handleServerRealityCheck(!1,null)},1E3*(m-p-5)),p=0):w&&(g-n+10<=p&&(p=0),l=setTimeout(function(){inGameRound||
c.handleServerRealityCheck(!1,null)},1E3*(g-n-p+10)),p=0)};this.handleClientRealityCheck=function(b){q=waitToEndRound=!1;-1<b.indexOf("MSGID=ERROR")&&-1<b.indexOf("<REALITYCHECK")&&(q=!0);var d="",a="",k=null,f=$.xml2json(b);~b.indexOf("TITLE")&&(d=f.REALITYCHECK.TITLE);if(~b.indexOf("TEXT")){a=f.REALITYCHECK.TEXT;try{k=JSON.parse(a),a=k.message}catch(x){}}~b.indexOf("OPTIONS")&&$.each(f.MESSAGE.OPTIONS.OPTION,function(b,a){c.RC_ACTION_TEXT[0]==a?(""!=a.action&&(c.RC_NOTIFICATION_LINK[0]=decodeURIComponent(a.action)),
t.push(wrappertexts.language[h].reality_check_proceed)):c.RC_ACTION_TEXT[1]==a?(""!=a.action&&(c.RC_NOTIFICATION_LINK[1]=decodeURIComponent(a.action)),t.push(wrappertexts.language[h].reality_check_exit)):c.RC_ACTION_TEXT[2]==a&&-1==B.indexOf(opid)?(""!=a.action&&(c.RC_NOTIFICATION_LINK[2]=decodeURIComponent(a.action)),t.push(wrappertexts.language[h].reality_check_history)):c.RC_ACTION_TEXT[3]==a&&""!=a.action&&(c.RC_NOTIFICATION_LINK[3]=decodeURIComponent(a.action))});if(0==t.length)c.startLocalTimer();
else{q||(wrapperinterface?(gameAPI("STOP_AUTOPLAY",!0),gameAPI("DISABLE_UI",!0)):(gameiframe.contentWindow.apiExt("PAUSE_AUTOPLAY",!0),gameiframe.contentWindow.apiExt("ENABLE_ALL_UI",!1)));""==d&&(d=wrappertexts.language[h].reality_check_title);""==a&&("en_us"==h||"en"==h?3600<e?(a=Math.floor(e/3600),b=Math.round((e-3600*a)/60),a=0==b?"You have been playing for "+a+" hour(s). Press CONTINUE to keep playing":"You have been playing for "+a+" hour(s) and "+b+" minute(s). Press CONTINUE to keep playing"):
60<e?(b=Math.floor(e/60),a=e%60,a=0==a?"You have been playing for "+b+" minute(s). Press CONTINUE to keep playing":"You have been playing for "+b+" minute(s) and "+a+" second(s). Press CONTINUE to keep playing"):a="You have been playing for "+e+" second(s). Press CONTINUE to keep playing":a=0==e%60?wrappertexts.language[h].reality_check_text.replace("%1",(e/60).toFixed(0)):wrappertexts.language[h].reality_check_text.replace("%1",(e/60).toFixed(1)));a=a.replace(/\\n/g,"<br/>");~B.indexOf(opid)&&(a+=
'<p><span style="font-size: 16px;">Game history is available under the "My account" menu</span></p>');null!=l&&(clearTimeout(l),l=null);b=null!=k?"REALITY_CHECK_CUSTOM":"OGS_REALITY_CHECK";try{f.OGS_RC&&(b=f.OGS_RC)}catch(x){console.warn(x)}f=a;var y=null!=k?k.errorParameters:null;try{y=JSON.parse(y)}catch(x){}d={realityCheckInfo:null!=k?{operatorError:{code:k.errorCode,message:a,params:y}}:{jurisdiction:"UK",sessionTime:e,realityCheckPeriod:g,title:d,options:{proceed:{label:t[0],value:u},exit:{label:t[1],
value:v},history:{label:t[2],value:z}}}};resumable=!0;gcmObj.handleError("REALITY_CHECK","ERROR",b,f,d)}};this.resumeRealityCheck=function(){q&&resendLastMessage();n=0;null!=l&&(clearTimeout(l),l=null);var b=c.RC_ACTION_TEXT[0];q||c.handleServerRealityCheck(!0,b);e+=g;0<m&&(m=10);wrapperinterface?(gameAPI("STOP_AUTOPLAY",!1),gameAPI("DISABLE_UI",!1)):(gameiframe.contentWindow.apiExt("ENABLE_ALL_UI",!0),gameiframe.contentWindow.apiExt("PAUSE_AUTOPLAY",!1));c.startLocalTimer()};var D=function(b,c){var a=
"<gdmRequest><currency>"+urlParameters.currency+"</currency><mode>"+urlParameters.mode+"</mode><lang>"+nogsLang+"</lang><gameName>"+urlParameters.gameName+"</gameName><token>"+urlParameters.token+"</token>";a=0<urlParameters.variant.length?a+("<variant>"+urlParameters.variant+"</variant>"):a+"<variant/>";a+="<methodName>ping</methodName><payload></payload>";b&&(a+='<jurisdiction code = "uk"><realityCheck><resetTimer>true</resetTimer><action>'+c+"</action></realityCheck></jurisdiction>");return a+
"</gdmRequest>"};this.createXmlRealityCheckInit=function(){var b="";w&&(b=Math.floor(Date.now()/1E3),0==r&&(r=b),p=b-r,b='<jurisdiction code = "uk"><realityCheck><limit>'+g+"</limit><elapsed>"+n+"</elapsed><proceed>"+u+"</proceed><exit>"+v+"</exit><history/><autospin>"+A+"</autospin><timestamp>"+r+"</timestamp></realityCheck></jurisdiction>");return b=b.replace(/&/g,"&amp;").replace(/%23/g,"#")};this.handleServerRealityCheck=function(b,d){var a="true"==urlParameters.secure?"https://"+urlParameters.serverAddress:
"http://"+urlParameters.serverAddress;a+="?dummy="+Date.now();d=D(b,d);urlParameters.rc_cookies?$.ajax({url:a,type:"POST",timeout:3E4,data:d,processData:!1,dataType:"xml",xhrFields:{withCredentials:!0},headers:{"Content-Type":"text/xml","Access-Control-Allow-Origin":"*"},success:function(a){var f=(new XMLSerializer).serializeToString(a),d=$.xml2json(f),k=null!=lastXmlResponse&&null!=lastResponse&&lastResponse.MESSAGE?lastResponse.MESSAGE:null;lastResponse=d;lastResponse.MESSAGE?lastXmlResponse=a:
null!=k&&(lastResponse.MESSAGE=k);if(!b)if(~f.indexOf("<REALITYCHECK"))"true"==d.REALITYCHECK.EXPIRED?(m=0,c.handleClientRealityCheck(f)):"false"==d.REALITYCHECK.EXPIRED&&(m=Number(d.REALITYCHECK.REMAININGTIME),realitycheck_uk_SESSIONTIME=Number(d.REALITYCHECK.SESSIONTIME),c.startLocalTimer());else try{lastResponse.MESSAGE?showOperatorMessage():c.startLocalTimer()}catch(C){c.startLocalTimer()}},error:function(a,b,c){}}):$.ajax({url:a,type:"POST",timeout:3E4,data:d,processData:!1,dataType:"xml",headers:{"Content-Type":"text/xml",
"Access-Control-Allow-Origin":"*"},success:function(a){var d=(new XMLSerializer).serializeToString(a),e=$.xml2json(d);if(!b){var k=null!=lastXmlResponse&&null!=lastResponse&&lastResponse.MESSAGE?lastResponse.MESSAGE:null;lastResponse=e;lastResponse.MESSAGE?lastXmlResponse=a:null!=k&&(lastResponse.MESSAGE=k);if(~d.indexOf("<REALITYCHECK"))"true"==e.REALITYCHECK.EXPIRED?(m=0,c.handleClientRealityCheck(d)):"false"==e.REALITYCHECK.EXPIRED&&(n=Number(e.REALITYCHECK.elapsedtime),m=Number(e.REALITYCHECK.REMAININGTIME),
c.startLocalTimer());else try{lastResponse.MESSAGE?showOperatorMessage():c.startLocalTimer()}catch(C){c.startLocalTimer()}}},error:function(a,b,c){}})};this.handleRealityCheckFromGDMResponse=function(b){var d=$.xml2json(b);if(~b.indexOf("<REALITYCHECK"))"true"==d.REALITYCHECK.EXPIRED?~b.indexOf("MSGID=INIT")?(e=n,0<e?c.handleClientRealityCheck(b):c.startLocalTimer()):-1==b.indexOf("MSGID=INIT")&&-1==b.indexOf("MSGID=REELSTRIP")&&(waitToEndRound=!0):"false"==d.REALITYCHECK.EXPIRED&&(m=Number(d.REALITYCHECK.REMAININGTIME),
n=Number(d.REALITYCHECK.elapsedTime),c.startLocalTimer());else if(~b.indexOf("MSGID=INIT"))try{lastResponse.MESSAGE?"undefined"===typeof lastResponse.MESSAGE.OPTIONS&&c.startLocalTimer():c.startLocalTimer()}catch(a){c.startLocalTimer()}};this.handleOperatorNotification=function(b,d,a,e){if(b==this.RC_ACTION_TEXT[0])if(q&&resendLastMessage(),""!=this.RC_NOTIFICATION_LINK[0])var f=this.RC_NOTIFICATION_LINK[0];else{wrapperinterface?(gameAPI("STOP_AUTOPLAY",!1),gameAPI("DISABLE_UI",!1)):(gameiframe.contentWindow.apiExt("ENABLE_ALL_UI",
!0),gameiframe.contentWindow.apiExt("PAUSE_AUTOPLAY",!1));return}else if(b==this.RC_ACTION_TEXT[1])""!=this.RC_NOTIFICATION_LINK[1]?f=this.RC_NOTIFICATION_LINK[1]:0<urlParameters.lobby.length?window!=window.top?window.top.location.href=urlParameters.lobby:window.location.href=urlParameters.lobby:window.location.href="exitgame.html";else{if(b==this.RC_ACTION_TEXT[2])return;if(b==this.RC_ACTION_TEXT[3])if(""!=this.RC_NOTIFICATION_LINK[3])f=this.RC_NOTIFICATION_LINK[3]+"?spins="+d+"&losslimit="+(0<a?
a/100:a)+"&singlewinlimit="+(0<e?e/100:e);else return}d="url="+encodeURIComponent(f)+"&REALITYCHECK="+b;urlParameters.rc_cookies?$.ajax({url:f,type:"GET",data:d,cache:!1,xhrFields:{withCredentials:!0},success:function(a){b==c.RC_ACTION_TEXT[0]?wrapperinterface?(gameAPI("STOP_AUTOPLAY",!1),gameAPI("DISABLE_UI",!1)):(gameiframe.contentWindow.apiExt("ENABLE_ALL_UI",!0),gameiframe.contentWindow.apiExt("PAUSE_AUTOPLAY",!1)):b==c.RC_ACTION_TEXT[1]&&(0<urlParameters.lobby.length?window!=window.top?window.top.location.href=
urlParameters.lobby:window.location.href=urlParameters.lobby:window.location.href="exitgame.html")},error:function(a,b,c){console.log("notification error")}}):$.ajax({url:f,type:"GET",data:d,cache:!1,success:function(a){b==c.RC_ACTION_TEXT[0]?wrapperinterface?(gameAPI("STOP_AUTOPLAY",!1),gameAPI("DISABLE_UI",!1)):(gameiframe.contentWindow.apiExt("ENABLE_ALL_UI",!0),gameiframe.contentWindow.apiExt("PAUSE_AUTOPLAY",!1)):b==c.RC_ACTION_TEXT[1]&&(0<urlParameters.lobby.length?window!=window.top?window.top.location.href=
urlParameters.lobby:window.location.href=urlParameters.lobby:window.location.href="exitgame.html")},error:function(a,b,c){console.log("notification error")}})}}var autoPlayNotification=function(h,q,g){null!=realityCheck&&realityCheck.handleOperatorNotification(realityCheck.RC_ACTION_TEXT[3],h,q,g)};
/* Version 3.0.17 Date: 20200514 */
