
const DEFAULT_TXT_ERROR_WAGER_FAILED = "Error wager failed";
var wrappertexts = {
	"language": {
		"en_us": {
					"reality_check_title": 		"Reality Check",
					"reality_check_text": 		"You have been playing for %1 minutes. Press CONTINUE to keep playing",
					"reality_check_proceed":	"Continue",
					"reality_check_exit":		"Exit",
					"reality_check_history":	"Account History",
					
					
					"MESSAGE_BTN_NO":			"No",
					"MESSAGE_BTN_YES": 			"Yes",
					"MESSAGE_BTN_CANCEL": 		"Cancel",
					"MESSAGE_BTN_SUBMIT": 		"Submit",
					"MESSAGE_BTN_OK": 			"OK",
					
					
					"MESSAGE_TITLE_PLAY_SLOT": "Play Slot",
                    "MESSAGE_TEXT_PLAY_SLOT":  "Are you sure you want to play slot game?",
					
					"MESSAGE_FULL_SCREEN":		"Full screen?",

					"TXT_WARNING":					"Warning",
					"TXT_ERROR":					"Error",
					"TXT_ERROR_PROTOCOL":			"Unknown protocol message",
					"TXT_ERROR_PROTOCOL_SEQUENCE":	"Incorrect Sequence of messages",
					"TXT_ERROR_UNKNOWN_PARAMETER":	"Unknown parameter in protocol",
					"TXT_ERROR_MISSING_PARAMETER":	"Missing parameter in protocol",
					"TXT_ERROR_PARAMETER_VALUE":	"Parameter Values is wrong",
					"TXT_ERROR_BET_LIMITS":			"Bet amount out of limits",
					"TXT_ERROR_LINES":				"Incorrect number of lines",
					"TXT_ERROR_FEATURE_PARAMETERS":	"Feature Parameters incorrect",
					"TXT_ERROR_JACKPOT":			"Unknown Jackpot error",
					"TXT_ERROR_UNKNOWN":			"Unknown error",
					"TXT_ERROR_NULL":				"Server communications lost",
					"TXT_ERROR_INSUFFICIENTFUNDS":	"Not enough balance for the Bet",
					"TXT_ERROR_STATESAVE":			"Error trying to save the state",
					"TXT_ERROR_STARTGAME":			"Error trying to start the game",
					"TXT_ERROR_ENDGAME":			"Error trying to end the game",
					"TXT_ERROR_GAMENOTSUPPORTED":	"Game isn't supported by the system",
					"TXT_ERROR_TIMEOUT":			"You have been disconnected from the Server.  Please restart the game.",
					"TXT_SERVLET_ERROR":			"Server communications lost",
					"TXT_ERROR_DEFAULT":			"Server communications lost",
					"TXT_ERROR_GAMING_LIMITS":		"Gaming limits reached",
					"TXT_ERROR_INVALID_SESSION":	"Player session is not valid",
					"TXT_ERROR_ACCOUNT_BLOCKED":	"Player account locked",
					"TXT_ERROR_WAGER_FAILED":       DEFAULT_TXT_ERROR_WAGER_FAILED
			},
		"en": {
					"reality_check_title": 		"Reality Check",
					"reality_check_text": 		"You have been playing for %1 minutes. Press CONTINUE to keep playing",
					"reality_check_proceed":	"Continue",
					"reality_check_exit":		"Exit",
					"reality_check_history":	"Account History",
					
					
					"MESSAGE_BTN_NO":			"No",
					"MESSAGE_BTN_YES": 			"Yes",
					"MESSAGE_BTN_CANCEL": 		"Cancel",
					"MESSAGE_BTN_SUBMIT": 		"Submit",
					"MESSAGE_BTN_OK": 			"OK",
					
					"MESSAGE_TITLE_PLAY_SLOT": "Play Slot",
                    "MESSAGE_TEXT_PLAY_SLOT":  "Are you sure you want to play slot game?",
					
					"MESSAGE_FULL_SCREEN":		"Full screen?",

					"TXT_WARNING":					"Warning",
					"TXT_ERROR":					"Error",
					"TXT_ERROR_PROTOCOL":			"Unknown protocol message",
					"TXT_ERROR_PROTOCOL_SEQUENCE":	"Incorrect Sequence of messages",
					"TXT_ERROR_UNKNOWN_PARAMETER":	"Unknown parameter in protocol",
					"TXT_ERROR_MISSING_PARAMETER":	"Missing parameter in protocol",
					"TXT_ERROR_PARAMETER_VALUE":	"Parameter Values is wrong",
					"TXT_ERROR_BET_LIMITS":			"Bet amount out of limits",
					"TXT_ERROR_LINES":				"Incorrect number of lines",
					"TXT_ERROR_FEATURE_PARAMETERS":	"Feature Parameters incorrect",
					"TXT_ERROR_JACKPOT":			"Unknown Jackpot error",
					"TXT_ERROR_UNKNOWN":			"Unknown error",
					"TXT_ERROR_NULL":				"Server communications lost",
					"TXT_ERROR_INSUFFICIENTFUNDS":	"Not enough balance for the Bet",
					"TXT_ERROR_STATESAVE":			"Error trying to save the state",
					"TXT_ERROR_STARTGAME":			"Error trying to start the game",
					"TXT_ERROR_ENDGAME":			"Error trying to end the game",
					"TXT_ERROR_GAMENOTSUPPORTED":	"Game isn't supported by the system",
					"TXT_ERROR_TIMEOUT":			"You have been disconnected from the Server.  Please restart the game.",
					"TXT_SERVLET_ERROR":			"Server communications lost",
					"TXT_ERROR_DEFAULT":			"Server communications lost",
					"TXT_ERROR_GAMING_LIMITS":		"Gaming limits reached",
					"TXT_ERROR_INVALID_SESSION":	"Player session is not valid",
					"TXT_ERROR_ACCOUNT_BLOCKED":	"Player account locked",
					"TXT_ERROR_WAGER_FAILED":       DEFAULT_TXT_ERROR_WAGER_FAILED
			},
			
	    "bg_bg": {
					"reality_check_title": 		"Обратно в реалността",
					"reality_check_text": 		"Вие сте били играе за %1 минути! Натиснете ПРОДЪЛЖИ, за да продължите да играете",
					"reality_check_proceed":	"Продължи",
					"reality_check_exit":		"Изход",
					"reality_check_history":	"История на акаунт",
					
					
					"MESSAGE_BTN_NO":			"Не",
					"MESSAGE_BTN_YES": 			"Да",
					"MESSAGE_BTN_CANCEL": 		"Отказ",
					"MESSAGE_BTN_SUBMIT": 		"Изпрати",
					"MESSAGE_BTN_OK": 			"OK",
					
					"MESSAGE_TITLE_PLAY_SLOT": "Ще играете ли на тази слот игра",
                    "MESSAGE_TEXT_PLAY_SLOT":  "Сигурни ли сте, че искате да играете слот играта?",
					
					"MESSAGE_FULL_SCREEN":		"Цял екран?",

					"TXT_WARNING":					"Внимание",
					"TXT_ERROR":					"Грешка",
					"TXT_ERROR_PROTOCOL":			"Неизвестно протоколно съобщение",
					"TXT_ERROR_PROTOCOL_SEQUENCE":	"Неправилна последователност от съобщения",
					"TXT_ERROR_UNKNOWN_PARAMETER":	"Неизвестен параметър в протокола",
					"TXT_ERROR_MISSING_PARAMETER":	"Липсващ параметър в протокола",
					"TXT_ERROR_PARAMETER_VALUE":	"Грешна стойност на параметър",
					"TXT_ERROR_BET_LIMITS":			"Сумата на залога е извън лимита",
					"TXT_ERROR_LINES":				"Неправилен брой линии",
					"TXT_ERROR_FEATURE_PARAMETERS":	"Неправилен параметър на функция",
					"TXT_ERROR_JACKPOT":			"Неизвестна грешка на джакпот",
					"TXT_ERROR_UNKNOWN":			"Неизвестна грешка",
					"TXT_ERROR_NULL":				"Няма комуникация към сървъра",
					"TXT_ERROR_INSUFFICIENTFUNDS":	"Недостатъчен баланс за залог",
					"TXT_ERROR_STATESAVE":			"Грешка при опит за запис на състояние",
					"TXT_ERROR_STARTGAME":			"Грешка при опит за стартиране на играта",
					"TXT_ERROR_ENDGAME":			"Грешка при опит за край на играта",
					"TXT_ERROR_GAMENOTSUPPORTED":	"Играта не се поддържа от системата",
					"TXT_ERROR_TIMEOUT":			"Връзката към сървъра е прекъсната.  Рестартирайте играта.",
					"TXT_SERVLET_ERROR":			"Няма комуникация към сървъра",
					"TXT_ERROR_DEFAULT":			"Няма комуникация към сървъра",
					"TXT_ERROR_GAMING_LIMITS":		"Достигнати лимити за игра",
					"TXT_ERROR_INVALID_SESSION":	"Сесията на играча е невалидна",
					"TXT_ERROR_ACCOUNT_BLOCKED":	"Акаунтът на играча е заключен",
					"TXT_ERROR_WAGER_FAILED":       DEFAULT_TXT_ERROR_WAGER_FAILED
			},
			
		"cs_cz": {
					"reality_check_title": 		"Kontrola reality",
					"reality_check_text": 		"Byli jste hrát za %1 minut! Stisknutím POKRAČOVAT budete hrát dál",
					"reality_check_proceed":	"Pokračovat",
					"reality_check_exit":		"Exit",
					"reality_check_history":	"Historie účtu",
					
					
					"MESSAGE_BTN_NO":			"Ne",
					"MESSAGE_BTN_YES": 			"Ano",
					"MESSAGE_BTN_CANCEL": 		"Zrušit",
					"MESSAGE_BTN_SUBMIT": 		"Odeslat",
					"MESSAGE_BTN_OK": 			"OK",
					
					"MESSAGE_TITLE_PLAY_SLOT": "Hrát automat",
                    "MESSAGE_TEXT_PLAY_SLOT":  "Opravdu chcete hrát automat?",
					
					"MESSAGE_FULL_SCREEN":		"Plná obrazovka?",

					"TXT_WARNING":					"Varování",
					"TXT_ERROR":					"Chyba",
					"TXT_ERROR_PROTOCOL":			"Neznámá zpráva protokolu",
					"TXT_ERROR_PROTOCOL_SEQUENCE":	"Nesprávné pořadí zpráv",
					"TXT_ERROR_UNKNOWN_PARAMETER":	"Neznámý parametr v protokolu",
					"TXT_ERROR_MISSING_PARAMETER":	"Chybějící parametr v protokolu",
					"TXT_ERROR_PARAMETER_VALUE":	"Hodnota parametru je nesprávná",
					"TXT_ERROR_BET_LIMITS":			"Velikost sázky je špatná",
					"TXT_ERROR_LINES":				"Nesprávný počet řádků",
					"TXT_ERROR_FEATURE_PARAMETERS":	"Nesprávné parametry funkce",
					"TXT_ERROR_JACKPOT":			"Neznámá chyba jackpotu",
					"TXT_ERROR_UNKNOWN":			"Neznámá chyba",
					"TXT_ERROR_NULL":				"Selhala komunikace se serverem",
					"TXT_ERROR_INSUFFICIENTFUNDS":	"Nedostatečný zůstatek pro sázku",
					"TXT_ERROR_STATESAVE":			"Nastala chyba při ukládání stavu",
					"TXT_ERROR_STARTGAME":			"Nastala chyba při spouštění hry",
					"TXT_ERROR_ENDGAME":			"Nastala chyba při ukončování hry",
					"TXT_ERROR_GAMENOTSUPPORTED":	"Hra není podporována systémem",
					"TXT_ERROR_TIMEOUT":			"Byli jste odpojeni od serveru.  Restartujte prosím hru.",
					"TXT_SERVLET_ERROR":			"Selhala komunikace se serverem",
					"TXT_ERROR_DEFAULT":			"Selhala komunikace se serverem",
					"TXT_ERROR_GAMING_LIMITS":		"Bylo dosaženo herního limitu",
					"TXT_ERROR_INVALID_SESSION":	"Herní relace není platná",
					"TXT_ERROR_ACCOUNT_BLOCKED":	"Účet hráče je uzamčen",
					"TXT_ERROR_WAGER_FAILED":       DEFAULT_TXT_ERROR_WAGER_FAILED
			},
			
		"da_dk": {
					"reality_check_title": 		"Virkelighedstjek",
					"reality_check_text": 		"Du har været spillet i %1 minutter! Tryk FORTSÆT for at blive ved med at spille",
					"reality_check_proceed":	"Fortsæt",
					"reality_check_exit":		"Exit",
					"reality_check_history":	"Kontohistorik",
					
					
					"MESSAGE_BTN_NO":			"Nej",
					"MESSAGE_BTN_YES": 			"Ja",
					"MESSAGE_BTN_CANCEL": 		"Annuller",
					"MESSAGE_BTN_SUBMIT": 		"Indsend",
					"MESSAGE_BTN_OK": 			"OK",
					
					"MESSAGE_TITLE_PLAY_SLOT": "Spil spillemaskinen",
                    "MESSAGE_TEXT_PLAY_SLOT":  "Er du sikker på, du vil starte spillet med spillemaskinen?",
					
					"MESSAGE_FULL_SCREEN":		"Fuld skærm?",

					"TXT_WARNING":					"Advarsel",
					"TXT_ERROR":					"Fejl",
					"TXT_ERROR_PROTOCOL":			"Ukendt protokolbesked",
					"TXT_ERROR_PROTOCOL_SEQUENCE":	"Forkert beskedrækkefølge",
					"TXT_ERROR_UNKNOWN_PARAMETER":	"Ukendt parameter i protokol",
					"TXT_ERROR_MISSING_PARAMETER":	"Manglende parameter i protokol",
					"TXT_ERROR_PARAMETER_VALUE":	"Parameter værdier er forkerte",
					"TXT_ERROR_BET_LIMITS":			"Indsats størrelsen er uden for grænsen",
					"TXT_ERROR_LINES":				"Forkert antal linjer",
					"TXT_ERROR_FEATURE_PARAMETERS":	"Funktions parameter forkerte",
					"TXT_ERROR_JACKPOT":			"Ukendt jackpot-fejl",
					"TXT_ERROR_UNKNOWN":			"Ukendt fejl",
					"TXT_ERROR_NULL":				"Serverkommunikation mistet",
					"TXT_ERROR_INSUFFICIENTFUNDS":	"for lav saldo til indsatsen",
					"TXT_ERROR_STATESAVE":			"Fejl ved forsøg på at gemme",
					"TXT_ERROR_STARTGAME":			"Fejl ved forsøg på at starte spillet",
					"TXT_ERROR_ENDGAME":			"Fejl ved forsøg på at slutte spillet",
					"TXT_ERROR_GAMENOTSUPPORTED":	"Spillet understøttes ikke af systemet",
					"TXT_ERROR_TIMEOUT":			"Du er blevet koblet af serveren. Genstart venligst spillet.",
					"TXT_SERVLET_ERROR":			"Serverkommunikation mistet",
					"TXT_ERROR_DEFAULT":			"Serverkommunikation mistet",
					"TXT_ERROR_GAMING_LIMITS":		"Spilgrænserne er nået",
					"TXT_ERROR_INVALID_SESSION":	"Spillersessionen er ikke gyldig",
					"TXT_ERROR_ACCOUNT_BLOCKED":	"Spillerkontoen er låst",
					"TXT_ERROR_WAGER_FAILED":       DEFAULT_TXT_ERROR_WAGER_FAILED
			},
			
		"de_de": {
					"reality_check_title": 		"Realitäts-Check",
					"reality_check_text": 		"Du bist gewesen %1 Minuten gespielt! Zum Weiterspielen auf FORTFAHREN  drücken",
					"reality_check_proceed":	"Fortfahren",
					"reality_check_exit":		"Beenden",
					"reality_check_history":	"Kontoverlauf",
					
					
					"MESSAGE_BTN_NO":			"Nein",
					"MESSAGE_BTN_YES": 			"Ja",
					"MESSAGE_BTN_CANCEL": 		"Abbrechen",
					"MESSAGE_BTN_SUBMIT": 		"Senden",
					"MESSAGE_BTN_OK": 			"OK",
					
					"MESSAGE_TITLE_PLAY_SLOT": "Spielautomaten spielen",
                    "MESSAGE_TEXT_PLAY_SLOT":  "Sind Sie sicher, dass Sie an einem Spielautomaten spielen möchten?",
					
					"MESSAGE_FULL_SCREEN":		"Vollbild?",

					"TXT_WARNING":					"Warnung",
					"TXT_ERROR":					"Fehler",
					"TXT_ERROR_PROTOCOL":			"Unbekannte Protokollnachricht",
					"TXT_ERROR_PROTOCOL_SEQUENCE":	"Falsche Nachrichtenreihenfolge",
					"TXT_ERROR_UNKNOWN_PARAMETER":	"Unbekannter Parameter im Protokoll",
					"TXT_ERROR_MISSING_PARAMETER":	"Fehlender Parameter im Protokoll",
					"TXT_ERROR_PARAMETER_VALUE":	"Falscher Parameterwert",
					"TXT_ERROR_BET_LIMITS":			"Einsatz übersteigt die Grenze",
					"TXT_ERROR_LINES":				"Ungültige Anzahl an Reihen",
					"TXT_ERROR_FEATURE_PARAMETERS":	"Falsche Bonusspielparameter",
					"TXT_ERROR_JACKPOT":			"Unbekannter Jackpot-Fehler",
					"TXT_ERROR_UNKNOWN":			"Unbekannter Fehler",
					"TXT_ERROR_NULL":				"Verbindung mit Server unterbrochen",
					"TXT_ERROR_INSUFFICIENTFUNDS":	"Zu wenig Guthaben für Einsatz",
					"TXT_ERROR_STATESAVE":			"Fehler beim Speichern des Status",
					"TXT_ERROR_STARTGAME":			"Fehler beim Starten des Spiels",
					"TXT_ERROR_ENDGAME":			"Fehler beim Beenden des Spiels",
					"TXT_ERROR_GAMENOTSUPPORTED":	"Das Spiel wird von Ihrem System nicht unterstützt",
					"TXT_ERROR_TIMEOUT":			"Die Verbindung mit dem Server wurde unterbrochen. Bitte starten Sie das Spiel neu.",
					"TXT_SERVLET_ERROR":			"Verbindung mit Server unterbrochen",
					"TXT_ERROR_DEFAULT":			"Verbindung mit Server unterbrochen",
					"TXT_ERROR_GAMING_LIMITS":		"Spielgrenzen erreicht",
					"TXT_ERROR_INVALID_SESSION":	"Spielersitzung ist ungültig",
					"TXT_ERROR_ACCOUNT_BLOCKED":	"Spielerkonto gesperrt",
					"TXT_ERROR_WAGER_FAILED":       DEFAULT_TXT_ERROR_WAGER_FAILED
			},
			
		"el_gr": {
					"reality_check_title": 		"Έλεγχος πραγματικότητας",
					"reality_check_text": 		"Εσείς έχω ήταν παιχνίδι %1 λεπτά! Πατήστε ΣΥΝΕΧΕΙΑ για να συνεχίσετε να παίζετε",
					"reality_check_proceed":	"Συνέχεια",
					"reality_check_exit":		"Εξοδοσ",
					"reality_check_history":	"Ιστορικό λογαριασμού",
					
					
					"MESSAGE_BTN_NO":			"Όχι",
					"MESSAGE_BTN_YES": 			"Ναι",
					"MESSAGE_BTN_CANCEL": 		"Άκυρο",
					"MESSAGE_BTN_SUBMIT": 		"Υποβολή",
					"MESSAGE_BTN_OK": 			"OK",
					
					"MESSAGE_TITLE_PLAY_SLOT": "Θέλετε να παίξετε κουλοχέρη",
                    "MESSAGE_TEXT_PLAY_SLOT":  "Είστε σίγουροι ότι επιθυμείτε να παίξετε παιχνίδι κουλοχέρη?",
					
					"MESSAGE_FULL_SCREEN":		"Πλήρης οθόνη?",

					"TXT_WARNING":					"Προειδοποίηση",
					"TXT_ERROR":					"Σφάλμα",
					"TXT_ERROR_PROTOCOL":			"Mήνυμα σε άγνωστο πρωτόκολλο",
					"TXT_ERROR_PROTOCOL_SEQUENCE":	"Εσφαλμένη ακολουθία μηνυμάτων",
					"TXT_ERROR_UNKNOWN_PARAMETER":	"Άγνωστη παράμετρος στο πρωτόκολλο",
					"TXT_ERROR_MISSING_PARAMETER":	"Λείπει παράμετρος στο πρωτόκολλο",
					"TXT_ERROR_PARAMETER_VALUE":	"Οι τιμές παραμέτρων είναι εσφαλμένες",
					"TXT_ERROR_BET_LIMITS":			"Ποσό στοιχήματος εκτός ορίων",
					"TXT_ERROR_LINES":				"Εσφαλμένος αριθμός γραμμών",
					"TXT_ERROR_FEATURE_PARAMETERS":	"Εσφαλμένες παράμετροι λειτουργιών",
					"TXT_ERROR_JACKPOT":			"Άγνωστο σφάλμα τζάκποτ",
					"TXT_ERROR_UNKNOWN":			"Άγνωστο σφάλμα",
					"TXT_ERROR_NULL":				"Απώλεια επικοινωνιών διακομιστή",
					"TXT_ERROR_INSUFFICIENTFUNDS":	"Ανεπαρκές υπόλοιπο για το στοίχημα",
					"TXT_ERROR_STATESAVE":			"Σφάλμα προσπάθειας αποθήκευσης της κατάστασης",
					"TXT_ERROR_STARTGAME":			"Σφάλμα κατά την εκκίνηση του παιχνιδιού",
					"TXT_ERROR_ENDGAME":			"Σφάλμα κατά την προσπάθεια τερματισμού του παιχνιδιού",
					"TXT_ERROR_GAMENOTSUPPORTED":	"Το παιχνίδι δεν υποστηρίζεται από το σύστημα",
					"TXT_ERROR_TIMEOUT":			"Έχετε αποσυνδεθεί από τον διακομιστή.  Επανεκκινήστε το παιχνίδι.",
					"TXT_SERVLET_ERROR":			"Απώλεια επικοινωνιών διακομιστή",
					"TXT_ERROR_DEFAULT":			"Απώλεια επικοινωνιών διακομιστή",
					"TXT_ERROR_GAMING_LIMITS":		"Συμπληρώθηκαν τα όρια στοιχηματισμού",
					"TXT_ERROR_INVALID_SESSION":	"Η συνεδρία παίκτη δεν είναι έγκυρη",
					"TXT_ERROR_ACCOUNT_BLOCKED":	"Ο λογαριασμός του παίκτη κλειδώθηκε",
					"TXT_ERROR_WAGER_FAILED":       DEFAULT_TXT_ERROR_WAGER_FAILED
			},
			
		"es_es": {
					"reality_check_title": 		"Comprobación de realidad",
					"reality_check_text": 		"Tú tener estado jugando %1 minutos! Para seguir jugando, pulse CONTINUAR",
					"reality_check_proceed":	"Continuar",
					"reality_check_exit":		"Salir",
					"reality_check_history":	"Historial de cuenta",
					
					
					"MESSAGE_BTN_NO":			"No",
					"MESSAGE_BTN_YES": 			"Sí",
					"MESSAGE_BTN_CANCEL": 		"Cancelar",
					"MESSAGE_BTN_SUBMIT": 		"Enviar",
					"MESSAGE_BTN_OK": 			"ACEPTAR",
					
					"MESSAGE_TITLE_PLAY_SLOT": "Jugar a la tragaperras",
                    "MESSAGE_TEXT_PLAY_SLOT":  "¿Seguro que desea jugar a la tragaperras?",
					
					"MESSAGE_FULL_SCREEN":		"¿Pantalla completa?",

					"TXT_WARNING":					"Advertencia",
					"TXT_ERROR":					"Error",
					"TXT_ERROR_PROTOCOL":			"Mensaje de protocolo desconocido",
					"TXT_ERROR_PROTOCOL_SEQUENCE":	"Secuencia de mensajes incorrecta",
					"TXT_ERROR_UNKNOWN_PARAMETER":	"Parámetro desconocido en el protocolo",
					"TXT_ERROR_MISSING_PARAMETER":	"Falta un parámetro en el protocolo",
					"TXT_ERROR_PARAMETER_VALUE":	"Los valores del parámetro son incorrectos",
					"TXT_ERROR_BET_LIMITS":			"Apuesta fuera de los límites",
					"TXT_ERROR_LINES":				"Número de líneas incorrecto",
					"TXT_ERROR_FEATURE_PARAMETERS":	"Parámetros de función incorrectos",
					"TXT_ERROR_JACKPOT":			"Error de bote desconocido",
					"TXT_ERROR_UNKNOWN":			"Error desconocido",
					"TXT_ERROR_NULL":				"Se ha perdido la comunicación con el servidor",
					"TXT_ERROR_INSUFFICIENTFUNDS":	"Saldo insuficiente para la apuesta",
					"TXT_ERROR_STATESAVE":			"Error al intentar guardar el estado",
					"TXT_ERROR_STARTGAME":			"Error al intentar iniciar la partida",
					"TXT_ERROR_ENDGAME":			"Error al intentar terminar la partida",
					"TXT_ERROR_GAMENOTSUPPORTED":	"El juego no es compatible con el sistema",
					"TXT_ERROR_TIMEOUT":			"Has sido desconectado del servidor. Reinicia la partida.",
					"TXT_SERVLET_ERROR":			"Se ha perdido la comunicación con el servidor",
					"TXT_ERROR_DEFAULT":			"Se ha perdido la comunicación con el servidor",
					"TXT_ERROR_GAMING_LIMITS":		"Se alcanzaron los límites de juego",
					"TXT_ERROR_INVALID_SESSION":	"La sesión del jugador no es válida",
					"TXT_ERROR_ACCOUNT_BLOCKED":	"La cuenta del jugador está bloqueada",
					"TXT_ERROR_WAGER_FAILED":       DEFAULT_TXT_ERROR_WAGER_FAILED
			},
			
		"et_ee": {
					"reality_check_title": 		"Reaalsuskontroll",
					"reality_check_text": 		"Sa olema olnud mängimine %1 minutit! Mängimise jätkamiseks vajuta JÄTKA",
					"reality_check_proceed":	"Jätka",
					"reality_check_exit":		"Välju",
					"reality_check_history":	"Konto ajalugu",
					
					
					"MESSAGE_BTN_NO":			"Ei",
					"MESSAGE_BTN_YES": 			"Jah",
					"MESSAGE_BTN_CANCEL": 		"Loobu",
					"MESSAGE_BTN_SUBMIT": 		"Saada",
					"MESSAGE_BTN_OK": 			"OK",	
					
					"MESSAGE_TITLE_PLAY_SLOT": "Mängime mänguautomaadil",
                    "MESSAGE_TEXT_PLAY_SLOT":  "Oled kindel, et soovid seda mänguautomaadi mängu mängida?",
					
					"MESSAGE_FULL_SCREEN":		"Täisekraan?",

					"TXT_WARNING":					"Hoiatus",
					"TXT_ERROR":					"Viga",
					"TXT_ERROR_PROTOCOL":			"Tundmatu protokolliteade",
					"TXT_ERROR_PROTOCOL_SEQUENCE":	"Vale sõnumite järjestus",
					"TXT_ERROR_UNKNOWN_PARAMETER":	"Tundmatu parameeter protokollis",
					"TXT_ERROR_MISSING_PARAMETER":	"Puuduv parameeter protokollis",
					"TXT_ERROR_PARAMETER_VALUE":	"Parameetri väärtused on valed",
					"TXT_ERROR_BET_LIMITS":			"Panuse summa pole piirides",
					"TXT_ERROR_LINES":				"Vale ridade arv",
					"TXT_ERROR_FEATURE_PARAMETERS":	"Boonusvõimaluse parameetrid valed",
					"TXT_ERROR_JACKPOT":			"Tundmatu jackpoti viga",
					"TXT_ERROR_UNKNOWN":			"Tundmatu viga",
					"TXT_ERROR_NULL":				"Ühendus serveriga katkes",
					"TXT_ERROR_INSUFFICIENTFUNDS":	"Panuse jaoks pole piisavalt vahendeid",
					"TXT_ERROR_STATESAVE":			"Oleku salvestamisel ilmnes viga",
					"TXT_ERROR_STARTGAME":			"Mängi käivitamisel ilmnes viga",
					"TXT_ERROR_ENDGAME":			"Mängi lõpetamisel ilmnes viga",
					"TXT_ERROR_GAMENOTSUPPORTED":	"Süsteem ei toeta mängu",
					"TXT_ERROR_TIMEOUT":			"Ühendus serveriga katkes.  Taaskäivita mäng.",
					"TXT_SERVLET_ERROR":			"Ühendus serveriga katkes",
					"TXT_ERROR_DEFAULT":			"Ühendus serveriga katkes",
					"TXT_ERROR_GAMING_LIMITS":		"Mängimislimiidid ületatud",
					"TXT_ERROR_INVALID_SESSION":	"Mängija seanss pole kehtiv",
					"TXT_ERROR_ACCOUNT_BLOCKED":	"Mängija konto lukustatud",
					"TXT_ERROR_WAGER_FAILED":       DEFAULT_TXT_ERROR_WAGER_FAILED
			},

         "eu_es": {
					"reality_check_title": 		"Itzuli errealitatera",
					"reality_check_text": 		"%1 minutuz aritu zara jokatzen. Sakatu JARRAITU, jokatzen jarraitzeko",
					"reality_check_proceed":	"Jarraitu",
					"reality_check_exit":		"Irten",
					"reality_check_history":	"Kontuaren historia",
					
					
					"MESSAGE_BTN_NO":			"Ez",
					"MESSAGE_BTN_YES": 			"Bai",
					"MESSAGE_BTN_CANCEL": 		"Utzi",
					"MESSAGE_BTN_SUBMIT": 		"Bidali",
					"MESSAGE_BTN_OK": 			"Ados",
					
					
					"MESSAGE_TITLE_PLAY_SLOT": "Jokatu txanpon-makinan",
                    "MESSAGE_TEXT_PLAY_SLOT":  "Ziur txanpon-makinako jokoan jokatu nahi duzula?",	

					"MESSAGE_FULL_SCREEN":		"Pantaila osoa?",

					 "TXT_WARNING":					"Abisua",
					 "TXT_ERROR":					"Errorea",
					 "TXT_ERROR_PROTOCOL":			"Protokolo-mezu ezezaguna",
					 "TXT_ERROR_PROTOCOL_SEQUENCE":	"Mezuen sekuentzia okerra",
					 "TXT_ERROR_UNKNOWN_PARAMETER":	"Parametro ezezaguna protokoloan",
					 "TXT_ERROR_MISSING_PARAMETER":	"Parametro bat falta da protokoloan",
					 "TXT_ERROR_PARAMETER_VALUE":	"Parametroaren balioak okerrak dira",
					 "TXT_ERROR_BET_LIMITS":			"Jokatutako kopurua mugetatik kanpokoa da",
					 "TXT_ERROR_LINES":				"Errenkada kopuru okerra",
					 "TXT_ERROR_FEATURE_PARAMETERS":	"Eginbide-parametroak okerrak dira",
					 "TXT_ERROR_JACKPOT":			"Sari nagusiaren errore ezezaguna",
					 "TXT_ERROR_UNKNOWN":			"Errore ezezaguna",
					 "TXT_ERROR_NULL":				"Zerbitzari-komunikazioak galdu dira",
					 "TXT_ERROR_INSUFFICIENTFUNDS":	"Ez dago apustua egiteko adina saldo",
					 "TXT_ERROR_STATESAVE":			"Errore bat gertatu da egoera gordetzean",
					 "TXT_ERROR_STARTGAME":			"Errore bat gertatu da jokoa hastean",
					 "TXT_ERROR_ENDGAME":			"Errore bat gertatu da jokoa amaitzean",
					 "TXT_ERROR_GAMENOTSUPPORTED":	"Sistemak ez du jokoa onartzen",
					 "TXT_ERROR_TIMEOUT":			"Zerbitzaritik deskonektatu zaituzte.  Berrabiarazi jokoa.",
					 "TXT_SERVLET_ERROR":			"Zerbitzari-komunikazioak galdu dira",
					 "TXT_ERROR_DEFAULT":			"Zerbitzari-komunikazioak galdu dira",
					 "TXT_ERROR_GAMING_LIMITS":		"Jokatzeko-mugak erdietsi dira",
					 "TXT_ERROR_INVALID_SESSION":	"Jokalariaren saioa ez da baliozkoa",
					 "TXT_ERROR_ACCOUNT_BLOCKED":	"Jokalariaren jokoa blokeatuta dago",
					 "TXT_ERROR_WAGER_FAILED":       DEFAULT_TXT_ERROR_WAGER_FAILED
			},
			
		"fi_sf": {
					"reality_check_title": 		"Tilannekatsau",
					"reality_check_text": 		"Sinä ollut pelaaminen %1 minuuttia! Jos haluat jatkaa pelaamista, paina JATKA",
					"reality_check_proceed":	"Jatka",
					"reality_check_exit":		"Poistu",
					"reality_check_history":	"Tilihistoria",
					
					
					"MESSAGE_BTN_NO":			"Ei",
					"MESSAGE_BTN_YES": 			"Kyllä",
					"MESSAGE_BTN_CANCEL": 		"Peruuta",
					"MESSAGE_BTN_SUBMIT": 		"Lähetä",
					"MESSAGE_BTN_OK": 			"OK",
					
					"MESSAGE_TITLE_PLAY_SLOT": "Pelataanko kolikkopeliä",
                    "MESSAGE_TEXT_PLAY_SLOT":  "Haluatko varmasti pelata kolikkopeliä?",
					
					"MESSAGE_FULL_SCREEN":		"Koko näytölle?",

					"TXT_WARNING":					"Varoitus",
					"TXT_ERROR":					"Virhe",
					"TXT_ERROR_PROTOCOL":			"Tuntematon protokollaviesti",
					"TXT_ERROR_PROTOCOL_SEQUENCE":	"Väärä viestijärjestys",
					"TXT_ERROR_UNKNOWN_PARAMETER":	"Tuntematon parametri protokollassa",
					"TXT_ERROR_MISSING_PARAMETER":	"Puuttuva parametri protokollassa",
					"TXT_ERROR_PARAMETER_VALUE":	"Parametrin arvot ovat vääriä",
					"TXT_ERROR_BET_LIMITS":			"Vetosumma on rajojen ulkopuolella",
					"TXT_ERROR_LINES":				"Väärä rivien määrä",
					"TXT_ERROR_FEATURE_PARAMETERS":	"Ominaisuuden parametrit ovat virheellisiä",
					"TXT_ERROR_JACKPOT":			"Tuntematon jättipottivirhe",
					"TXT_ERROR_UNKNOWN":			"Tuntematon virhe",
					"TXT_ERROR_NULL":				"Yhteys palvelimeen katkennut",
					"TXT_ERROR_INSUFFICIENTFUNDS":	"Saldo ei riitä panokseen",
					"TXT_ERROR_STATESAVE":			"Virhe tallennettaessa tilaa",
					"TXT_ERROR_STARTGAME":			"Virhe käynnistettäessä peliä",
					"TXT_ERROR_ENDGAME":			"Virhe lopetettaessa peliä",
					"TXT_ERROR_GAMENOTSUPPORTED":	"Järjestelmä ei tue peliä",
					"TXT_ERROR_TIMEOUT":			"Yhteys palvelimeen on katkennut.  Käynnistä peli uudelleen.",
					"TXT_SERVLET_ERROR":			"Yhteys palvelimeen katkennut",
					"TXT_ERROR_DEFAULT":			"Yhteys palvelimeen katkennut",
					"TXT_ERROR_GAMING_LIMITS":		"Pelirajat saavutettu",
					"TXT_ERROR_INVALID_SESSION":	"Pelaajan istunto ei kelpaa",
					"TXT_ERROR_ACCOUNT_BLOCKED":	"Pelaajatili lukittu",
					"TXT_ERROR_WAGER_FAILED":       DEFAULT_TXT_ERROR_WAGER_FAILED
			},	

		"fr_fr": {
					"reality_check_title": 		"Petit rappel rapide",
					"reality_check_text": 		"Vous avez joué %1 minutes ! Appuyez sur CONTINUER pour poursuivre votre partie",
					"reality_check_proceed":	"Continuer",
					"reality_check_exit":		"Sortir",
					"reality_check_history":	"Historique du compte",
					
					
					"MESSAGE_BTN_NO":			"Non",
					"MESSAGE_BTN_YES": 			"Oui",
					"MESSAGE_BTN_CANCEL": 		"Annuler",
					"MESSAGE_BTN_SUBMIT": 		"Envoyer",
					"MESSAGE_BTN_OK": 			"OK",
					
					"MESSAGE_TITLE_PLAY_SLOT": "Jouer aux machines à sous ",
                    "MESSAGE_TEXT_PLAY_SLOT":  "Voulez-vous vraiment jouer au bandit manchot?",
					
					
					"MESSAGE_FULL_SCREEN":		"Plein écran ?",

					"TXT_WARNING":					"Avertissement",
					"TXT_ERROR":					"Erreur",
					"TXT_ERROR_PROTOCOL":			"Message de protocole inconnu",
					"TXT_ERROR_PROTOCOL_SEQUENCE":	"Séquence de messages incorrecte",
					"TXT_ERROR_UNKNOWN_PARAMETER":	"Paramètre inconnu dans protocole",
					"TXT_ERROR_MISSING_PARAMETER":	"Paramètre manquant dans protocole",
					"TXT_ERROR_PARAMETER_VALUE":	"Les valeurs de paramètres sont erronées",
					"TXT_ERROR_BET_LIMITS":			"Montant misé hors limites",
					"TXT_ERROR_LINES":				"Nombre de lignes incorrect",
					"TXT_ERROR_FEATURE_PARAMETERS":	"Paramètres de fonction incorrects",
					"TXT_ERROR_JACKPOT":			"Erreur de jackpot inconnu",
					"TXT_ERROR_UNKNOWN":			"Erreur inconnue",
					"TXT_ERROR_NULL":				"Perte de communication avec le serveur",
					"TXT_ERROR_INSUFFICIENTFUNDS":	"Ajustez la mise ou ajoutez de l'argent pour continuer à jouer",
					"TXT_ERROR_STATESAVE":			"Erreur au cours de la sauvegarde de l'état",
					"TXT_ERROR_STARTGAME":			"Erreur au cours du démarrage du jeu",
					"TXT_ERROR_ENDGAME":			"Erreur lors de la fermeture du jeu",
					"TXT_ERROR_GAMENOTSUPPORTED":	"Le jeu n'est pas pris en charge par le système",
					"TXT_ERROR_TIMEOUT":			"Vous avez été déconnecté du serveur. Veuillez redémarrer le jeu.",
					"TXT_SERVLET_ERROR":			"Perte de communication avec le serveur",
					"TXT_ERROR_DEFAULT":			"Perte de communication avec le serveur",
					"TXT_ERROR_GAMING_LIMITS":		"Limites de jeu atteintes",
					"TXT_ERROR_INVALID_SESSION":	"La session du joueur n'est pas valide",
					"TXT_ERROR_ACCOUNT_BLOCKED":	"Compte du joueur verrouillé",
					"TXT_ERROR_WAGER_FAILED":       DEFAULT_TXT_ERROR_WAGER_FAILED
			},	
			
			
		"hr_hr": {
					"reality_check_title": 		"Podsjetnik",
					"reality_check_text": 		"Igrate %1 minuta. Pritisnite NASTAVI za nastavak igre",
					"reality_check_proceed":	"Nastavi",
					"reality_check_exit":		"Izađi",
					"reality_check_history":	"Povijest računa",
					
					
					"MESSAGE_BTN_NO":			"Ne",
					"MESSAGE_BTN_YES": 			"Da",
					"MESSAGE_BTN_CANCEL": 		"Odustani",
					"MESSAGE_BTN_SUBMIT": 		"Pošalji",
					"MESSAGE_BTN_OK": 			"U redu",
					
					
					"MESSAGE_TITLE_PLAY_SLOT": "Igraj na automatu",
                    "MESSAGE_TEXT_PLAY_SLOT":  "Jeste li sigurni da želite igrati na automatu?",
					
					
					"MESSAGE_FULL_SCREEN":		"Cijeli zaslon?",

					"TXT_WARNING":					"Upozorenje",
					"TXT_ERROR":					"Pogreška",
					"TXT_ERROR_PROTOCOL":			"Nepoznata poruka protokola",
					"TXT_ERROR_PROTOCOL_SEQUENCE":	"Netočan slijed poruka",
					"TXT_ERROR_UNKNOWN_PARAMETER":	"Nepoznati parametar u protokolu",
					"TXT_ERROR_MISSING_PARAMETER":	"Nedostaje parametar u protokolu",
					"TXT_ERROR_PARAMETER_VALUE":	"Vrijednosti parametra su netočne",
					"TXT_ERROR_BET_LIMITS":			"Iznos uloga je van granica",
					"TXT_ERROR_LINES":				"Netočan broj linija",
					"TXT_ERROR_FEATURE_PARAMETERS":	"Netočni parametri značajke",
					"TXT_ERROR_JACKPOT":			"Nepoznata pogreška jackpota",
					"TXT_ERROR_UNKNOWN":			"Nepoznata pogreška",
					"TXT_ERROR_NULL":				"Prekinuta je komunikacija s poslužiteljem",
					"TXT_ERROR_INSUFFICIENTFUNDS":	"Nedovoljan balans za ulog",
					"TXT_ERROR_STATESAVE":			"Greška prilikom pokušaja spremanja stanja",
					"TXT_ERROR_STARTGAME":			"Greška prilikom pokretanja igre",
					"TXT_ERROR_ENDGAME":			"Greška prilikom zaustavljanja igre",
					"TXT_ERROR_GAMENOTSUPPORTED":	"Sustav ne podupire ovu igru",
					"TXT_ERROR_TIMEOUT":			"Otpojeni ste s poslužitelja.  Molimo ponovno pokrenite igru.",
					"TXT_SERVLET_ERROR":			"Prekinuta je komunikacija s poslužiteljem",
					"TXT_ERROR_DEFAULT":			"Prekinuta je komunikacija s poslužiteljem",
					"TXT_ERROR_GAMING_LIMITS":		"Gaming ograničenja dosegao",
					"TXT_ERROR_INVALID_SESSION":	"Igrač sjednici nije važeći",
					"TXT_ERROR_ACCOUNT_BLOCKED":	"Igrač račun zaključan",
					"TXT_ERROR_WAGER_FAILED":       DEFAULT_TXT_ERROR_WAGER_FAILED
			},		
			
		"hu_hu": {
					"reality_check_title": 		"Valóságellenőrzés",
					"reality_check_text": 		"Te már játszott %1 perce! Nyomd meg a FOLYTATÁS gombot továbbjátszásához",
					"reality_check_proceed":	"Folytatás",
					"reality_check_exit":		"Kilépés",
					"reality_check_history":	"Számlaelőzmények",
					
					
					"MESSAGE_BTN_NO":			"Nem",
					"MESSAGE_BTN_YES": 			"Igen",
					"MESSAGE_BTN_CANCEL": 		"Mégse",
					"MESSAGE_BTN_SUBMIT": 		"Küldés",
					"MESSAGE_BTN_OK": 			"OK",
					
					"MESSAGE_TITLE_PLAY_SLOT": "Nyerőgép játszása",
                    "MESSAGE_TEXT_PLAY_SLOT":  "Biztos, hogy a nyerőgépen akarsz játszani?",
					
					"MESSAGE_FULL_SCREEN":		"Teljes képernyő?",

					"TXT_WARNING":					"Figyelmeztetés",
					"TXT_ERROR":					"Hiba",
					"TXT_ERROR_PROTOCOL":			"Ismeretlen protokoll-üzenet",
					"TXT_ERROR_PROTOCOL_SEQUENCE":	"Az üzenetek sorrendje hibás",
					"TXT_ERROR_UNKNOWN_PARAMETER":	"Ismeretlen paraméter a protokollban",
					"TXT_ERROR_MISSING_PARAMETER":	"Hiányzó paraméter a protokollban",
					"TXT_ERROR_PARAMETER_VALUE":	"A paraméter értékek hibásak",
					"TXT_ERROR_BET_LIMITS":			"A tét összege a határértékeken kívüli",
					"TXT_ERROR_LINES":				"A sorok száma hibás",
					"TXT_ERROR_FEATURE_PARAMETERS":	"A funkció-paraméterek hibásak",
					"TXT_ERROR_JACKPOT":			"Ismeretlen Jackpot hiba",
					"TXT_ERROR_UNKNOWN":			"Ismeretlen hiba",
					"TXT_ERROR_NULL":				"A kommunikáció a kiszolgálóval megszakadt",
					"TXT_ERROR_INSUFFICIENTFUNDS":	"Nincs elegendő egyenleg a tét megfogadásához",
					"TXT_ERROR_STATESAVE":			"Hiba az állapot mentése közben",
					"TXT_ERROR_STARTGAME":			"Hiba a játék indítása közben",
					"TXT_ERROR_ENDGAME":			"Hiba a játék befejezése közben",
					"TXT_ERROR_GAMENOTSUPPORTED":	"A rendszer nem támogatja a játékot",
					"TXT_ERROR_TIMEOUT":			"Megszakadt a kapcsolat a kiszolgálóval.  Kérjük, indítsa újra a játékot.",
					"TXT_SERVLET_ERROR":			"A kommunikáció a kiszolgálóval megszakadt",
					"TXT_ERROR_DEFAULT":			"A kommunikáció a kiszolgálóval megszakadt",
					"TXT_ERROR_GAMING_LIMITS":		"A játéklimit elérve",
					"TXT_ERROR_INVALID_SESSION":	"Érvénytelen játékos munkamenet",
					"TXT_ERROR_ACCOUNT_BLOCKED":	"A játékos számlája zárolva",
					"TXT_ERROR_WAGER_FAILED":       DEFAULT_TXT_ERROR_WAGER_FAILED
			},

		"it_it": {
					"reality_check_title": 		"Resoconto",
					"reality_check_text": 		"Hai giocato %1 minuti! Premi CONTINUA per continuare col divertimento",
					"reality_check_proceed":	"Continua",
					"reality_check_exit":		"Esci",
					"reality_check_history":	"Cronologia Conto",
					
					
					"MESSAGE_BTN_NO":			"No",
					"MESSAGE_BTN_YES": 			"Sì",
					"MESSAGE_BTN_CANCEL": 		"Annulla",
					"MESSAGE_BTN_SUBMIT": 		"Invia",
					"MESSAGE_BTN_OK": 			"OK",
					
					"MESSAGE_TITLE_PLAY_SLOT": "Giocare alla Slot",
                    "MESSAGE_TEXT_PLAY_SLOT":  "Sei sicuro di volere giocare alla slot?",
					
					"MESSAGE_FULL_SCREEN":		"Schermo intero?",

					"TXT_WARNING":					"Attenzione",
					"TXT_ERROR":					"Errore",
					"TXT_ERROR_PROTOCOL":			"Messaggio di protocollo sconosciuto",
					"TXT_ERROR_PROTOCOL_SEQUENCE":	"Sequenza di messaggi errata",
					"TXT_ERROR_UNKNOWN_PARAMETER":	"Parametro sconosciuto nel protocollo",
					"TXT_ERROR_MISSING_PARAMETER":	"Parametro assente nel protocollo",
					"TXT_ERROR_PARAMETER_VALUE":	"Il valore del parametro è errato",
					"TXT_ERROR_BET_LIMITS":			"L'importo della puntata non rientra nei limiti",
					"TXT_ERROR_LINES":				"Numero di linee errato",
					"TXT_ERROR_FEATURE_PARAMETERS":	"Parametri della giocata speciale errati",
					"TXT_ERROR_JACKPOT":			"Errore jackpot sconosciuto",
					"TXT_ERROR_UNKNOWN":			"Errore sconosciuto",
					"TXT_ERROR_NULL":				"Comunicazione con il server interrotta",
					"TXT_ERROR_INSUFFICIENTFUNDS":	"Saldo non sufficiente per la puntata",
					"TXT_ERROR_STATESAVE":			"Errore durante il tentativo di salvare lo stato",
					"TXT_ERROR_STARTGAME":			"Errore durante il tentativo di avviare il gioco",
					"TXT_ERROR_ENDGAME":			"Errore durante il tentativo di terminare la partita",
					"TXT_ERROR_GAMENOTSUPPORTED":	"Il gioco non è supportato dal sistema",
					"TXT_ERROR_TIMEOUT":			"Sei stato disconnesso dal server. Riavvia il gioco.",
					"TXT_SERVLET_ERROR":			"Comunicazione con il server interrotta",
					"TXT_ERROR_DEFAULT":			"Comunicazione con il server interrotta",
					"TXT_ERROR_GAMING_LIMITS":		"Limiti di gioco raggiunti",
					"TXT_ERROR_INVALID_SESSION":	"La sessione di gioco non è valida",
					"TXT_ERROR_ACCOUNT_BLOCKED":	"Account giocatore bloccato",
					"TXT_ERROR_WAGER_FAILED":       DEFAULT_TXT_ERROR_WAGER_FAILED
			},

		"ja_jp": {
					"reality_check_title": 		"現実性チェック",
					"reality_check_text": 		"あなたが演奏されています%1分！プレーを続けるには [続ける] をクリックします",
					"reality_check_proceed":	"続ける",
					"reality_check_exit":		"終了",
					"reality_check_history":	"アカウント履歴",
					
					
					"MESSAGE_BTN_NO":			"いいえ",
					"MESSAGE_BTN_YES": 			"はい",
					"MESSAGE_BTN_CANCEL": 		"キャンセル",
					"MESSAGE_BTN_SUBMIT": 		"送信",
					"MESSAGE_BTN_OK": 			"OK",
					
					"MESSAGE_TITLE_PLAY_SLOT": "スロットをプレーしますか",
                    "MESSAGE_TEXT_PLAY_SLOT":  "本当にスロットゲームをプレーしますか？",
					
					"MESSAGE_FULL_SCREEN":		"全画面表示をしますか？",

					"TXT_WARNING":					"警告",
					"TXT_ERROR":					"エラー",
					"TXT_ERROR_PROTOCOL":			"不明のプロトコル・メッセージ",
					"TXT_ERROR_PROTOCOL_SEQUENCE":	"メッセージのシーケンスが正しくありません。",
					"TXT_ERROR_UNKNOWN_PARAMETER":	"プロトコルに不明のパラメータがあります。",
					"TXT_ERROR_MISSING_PARAMETER":	"プロトコルのパラメータがありません。",
					"TXT_ERROR_PARAMETER_VALUE":	"パラメーター値が間違っています。",
					"TXT_ERROR_BET_LIMITS":			"ベットが上限を超えています。",
					"TXT_ERROR_LINES":				"ラインの数が正しくありません。",
					"TXT_ERROR_FEATURE_PARAMETERS":	"フィーチャーのパラメータが正しくありません。",
					"TXT_ERROR_JACKPOT":			"不明のジャックポット・エラー",
					"TXT_ERROR_UNKNOWN":			"不明のエラー",
					"TXT_ERROR_NULL":				"サーバ接続が途切れました。",
					"TXT_ERROR_INSUFFICIENTFUNDS":	"ベットするには残高が不足しています。",
					"TXT_ERROR_STATESAVE":			"ゲームの保存エラー",
					"TXT_ERROR_STARTGAME":			"ゲームの開始エラー",
					"TXT_ERROR_ENDGAME":			"ゲームの終了エラー",
					"TXT_ERROR_GAMENOTSUPPORTED":	"ゲームがシステムでサポートされていません。",
					"TXT_ERROR_TIMEOUT":			"お客様はサーバから切断されました。ゲームをやり直してください。",
					"TXT_SERVLET_ERROR":			"サーバ接続が途切れました。",
					"TXT_ERROR_DEFAULT":			"サーバ接続が途切れました。",
					"TXT_ERROR_GAMING_LIMITS":		"ゲーム限度額に達しました",
					"TXT_ERROR_INVALID_SESSION":	"プレイヤーセッションは無効です",
					"TXT_ERROR_ACCOUNT_BLOCKED":	"プレイヤーアカウントがロック (一時停止) されました",
					"TXT_ERROR_WAGER_FAILED":       DEFAULT_TXT_ERROR_WAGER_FAILED
			},

		"ka_ge": {
					"reality_check_title": 		"ნამდვილობის შემოწმება",
					"reality_check_text": 		"თქვენ აქვს ყოფილა სათამაშო % 1 წუთი! დააჭირეთ „გაგრძელებას“ თამაშის გასაგრძელებლად",
					"reality_check_proceed":	"გაგრძელება",
					"reality_check_exit":		"გასვლა",
					"reality_check_history":	"ანგარიშის ისტორია",
					
					
					"MESSAGE_BTN_NO":			"არა",
					"MESSAGE_BTN_YES": 			"დიახ",
					"MESSAGE_BTN_CANCEL": 		"გაუქმება",
					"MESSAGE_BTN_SUBMIT": 		"გაგზავნა",
					"MESSAGE_BTN_OK": 			"კარგი",
				
					"MESSAGE_TITLE_PLAY_SLOT": "გსურთ, ითამაშოთ სლოტი",
                    "MESSAGE_TEXT_PLAY_SLOT":  "დარწმუნებული ხართ, რომ სლოტის თამაშის გსურთ?",
					
					"MESSAGE_FULL_SCREEN":		"გსურთ სრულ ეკრანზე გადასვლა?",

					"TXT_WARNING":					"გაფრთხილება",
					"TXT_ERROR":					"შეცდომა",
					"TXT_ERROR_PROTOCOL":			"პროტოკოლის უცნობი შეტყობინება",
					"TXT_ERROR_PROTOCOL_SEQUENCE":	"შეტყობინებების არასწორი თანმიმდევრობა",
					"TXT_ERROR_UNKNOWN_PARAMETER":	"პროტოკოლის უცნობი პარამეტრი",
					"TXT_ERROR_MISSING_PARAMETER":	"პროტოკოლის პარამეტრი გამოტოვებულია",
					"TXT_ERROR_PARAMETER_VALUE":	"პარამეტრის სიდიდეები არასწორია",
					"TXT_ERROR_BET_LIMITS":			"ფსონის რაოდენობა საზღვრებს სცილდება",
					"TXT_ERROR_LINES":				"ხაზების არასწორი რაოდენობა",
					"TXT_ERROR_FEATURE_PARAMETERS":	"თამაშის ფუნქციის პარამეტრები არასწორია",
					"TXT_ERROR_JACKPOT":			"ჯეკპოტის უცნობი შეცდომა",
					"TXT_ERROR_UNKNOWN":			"უცნობი შეცდომა",
					"TXT_ERROR_NULL":				"სერვერთან დაკავშირება შეუძლებელია",
					"TXT_ERROR_INSUFFICIENTFUNDS":	"ფსონისათვის თანხის საკმარისი ბალანსი არ გაქვთ",
					"TXT_ERROR_STATESAVE":			"შეცდომა მდგომარეობის დამახსოვრების დროს",
					"TXT_ERROR_STARTGAME":			"შეცდომა თამაშის დაწყების დროს",
					"TXT_ERROR_ENDGAME":			"შეცდომა თამაშის დამთავრების დროს",
					"TXT_ERROR_GAMENOTSUPPORTED":	"სისტემას არ გააჩნია თამაშის მხარდაჭერა",
					"TXT_ERROR_TIMEOUT":			"სერვერს გამოეთიშეთ.  გთხოვთ ხელახლა დაიწყოთ თამაში.",
					"TXT_SERVLET_ERROR":			"სერვერთან დაკავშირება შეუძლებელია",
					"TXT_ERROR_DEFAULT":			"სერვერთან დაკავშირება შეუძლებელია",
					"TXT_ERROR_GAMING_LIMITS":		"თქვენ მიაღწიეთ თამაშის ლიმიტს ",
					"TXT_ERROR_INVALID_SESSION":	"მოთამაშის სეანსი არასწორია",
					"TXT_ERROR_ACCOUNT_BLOCKED":	"მოთამაშის ანგარიში დაბლოკილია",
					"TXT_ERROR_WAGER_FAILED":       DEFAULT_TXT_ERROR_WAGER_FAILED
			},

		"ko_kr": {
					"reality_check_title": 		"현실 확인",
					"reality_check_text": 		"당신 있다 하고 재생 %1분! 계속하기를 눌러서 계속 플레이하세요",
					"reality_check_proceed":	"계속하기",
					"reality_check_exit":		"나가기",
					"reality_check_history":	"계정 기록",
					
					
					"MESSAGE_BTN_NO":			"아니요",
					"MESSAGE_BTN_YES": 			"예",
					"MESSAGE_BTN_CANCEL": 		"취소",
					"MESSAGE_BTN_SUBMIT": 		"제출",
					"MESSAGE_BTN_OK": 			"확인",
					
					"MESSAGE_TITLE_PLAY_SLOT": "슬롯을 플레이할까요",
                    "MESSAGE_TEXT_PLAY_SLOT":  "슬롯 게임을 플레이하시겠습니까?",
					
					"MESSAGE_FULL_SCREEN":		"전체 화면?",

					"TXT_WARNING":					"주의",
					"TXT_ERROR":					"오류",
					"TXT_ERROR_PROTOCOL":			"알 수 없는 프로토콜 메시지",
					"TXT_ERROR_PROTOCOL_SEQUENCE":	"올바르지 않은 메시지 시퀀스",
					"TXT_ERROR_UNKNOWN_PARAMETER":	"프로토콜에 알 수 없는 파라미터가 있음",
					"TXT_ERROR_MISSING_PARAMETER":	"프로토콜에서 파라미터 누락",
					"TXT_ERROR_PARAMETER_VALUE":	"잘못된 파라미터 값",
					"TXT_ERROR_BET_LIMITS":			"베팅 액수 한도 초과",
					"TXT_ERROR_LINES":				"올바르지 않은 라인 수",
					"TXT_ERROR_FEATURE_PARAMETERS":	"기능 파라미터가 올바르지 않음",
					"TXT_ERROR_JACKPOT":			"알 수 없는 잭팟 오류",
					"TXT_ERROR_UNKNOWN":			"알 수 없는 오류",
					"TXT_ERROR_NULL":				"서버 통신 단절",
					"TXT_ERROR_INSUFFICIENTFUNDS":	"베팅에 필요한 잔액 부족",
					"TXT_ERROR_STATESAVE":			"상태를 저장하는 도중 오류 발생",
					"TXT_ERROR_STARTGAME":			"게임을 시작하는 도중 오류 발생",
					"TXT_ERROR_ENDGAME":			"게임을 종료하는 도중 오류 발생",
					"TXT_ERROR_GAMENOTSUPPORTED":	"시스템에서 이 게임을 지원하지 않습니다.",
					"TXT_ERROR_TIMEOUT":			"서버에서 연결이 끊어졌습니다.  게임을 다시 시작하십시오.",
					"TXT_SERVLET_ERROR":			"서버 통신 단절",
					"TXT_ERROR_DEFAULT":			"서버 통신 단절",
					"TXT_ERROR_GAMING_LIMITS":		"게임 한계에 도달했습니다",
					"TXT_ERROR_INVALID_SESSION":	"플레이어 세션이 유효하지 않습니다",
					"TXT_ERROR_ACCOUNT_BLOCKED":	"플레이어 계정이 잠겼습니다",
					"TXT_ERROR_WAGER_FAILED":       DEFAULT_TXT_ERROR_WAGER_FAILED
			},

		"lv_lv": {
					"reality_check_title": 		"Realitātes pārbaude",
					"reality_check_text": 		"Tu būt ir spēlē %1 minūtes! Nospiediet TURPINĀT, lai turpinātu spēlēt",
					"reality_check_proceed":	"Turpināt",
					"reality_check_exit":		"Iziet",
					"reality_check_history":	"Konta vēsture",
					
					
					"MESSAGE_BTN_NO":			"Nē",
					"MESSAGE_BTN_YES": 			"Jā",
					"MESSAGE_BTN_CANCEL": 		"Atcelt",
					"MESSAGE_BTN_SUBMIT": 		"Iesniegt",
					"MESSAGE_BTN_OK": 			"LABI",
					
					"MESSAGE_TITLE_PLAY_SLOT": "Vai spēlēt spēļu automāta spēli",
                    "MESSAGE_TEXT_PLAY_SLOT":  "Vai tiešām vēlies spēlēt šo spēļu automāta spēli?",
					
					"MESSAGE_FULL_SCREEN":		"Pilnekrāns?",

					"TXT_WARNING":					"Brīdinājums",
					"TXT_ERROR":					"Kļūda",
					"TXT_ERROR_PROTOCOL":			"Nezināms protokola ziņojums",
					"TXT_ERROR_PROTOCOL_SEQUENCE":	"Nepareiza ziņojumu secība",
					"TXT_ERROR_UNKNOWN_PARAMETER":	"Nezināms protokola parametrs",
					"TXT_ERROR_MISSING_PARAMETER":	"Trūkst protokola parametra",
					"TXT_ERROR_PARAMETER_VALUE":	"Nepareizas parametru vērtības",
					"TXT_ERROR_BET_LIMITS":			"Likmes summa neatbilst ierobežojumiem",
					"TXT_ERROR_LINES":				"Nepareizs līniju skaits",
					"TXT_ERROR_FEATURE_PARAMETERS":	"Nepareizi funkciju parametri",
					"TXT_ERROR_JACKPOT":			"Nezināma džekpota kļūda",
					"TXT_ERROR_UNKNOWN":			"Nezināma kļūda",
					"TXT_ERROR_NULL":				"Zudis savienojums ar serveri",
					"TXT_ERROR_INSUFFICIENTFUNDS":	"Nepietiekams atlikums likmes veikšanai",
					"TXT_ERROR_STATESAVE":			"Kļūda, mēģinot saglabāt statusu",
					"TXT_ERROR_STARTGAME":			"Kļūda, mēģinot sākt spēli",
					"TXT_ERROR_ENDGAME":			"Kļūda, mēģinot beigt spēli",
					"TXT_ERROR_GAMENOTSUPPORTED":	"Sistēmā nav nodrošināts spēles atbalsts",
					"TXT_ERROR_TIMEOUT":			"Ir pārtraukts savienojums ar serveri.  Lūdzu, vēlreiz sāciet spēli.",
					"TXT_SERVLET_ERROR":			"Zudis savienojums ar serveri",
					"TXT_ERROR_DEFAULT":			"Zudis savienojums ar serveri",
					"TXT_ERROR_GAMING_LIMITS":		"Sasniegtas derību robežvērtības",
					"TXT_ERROR_INVALID_SESSION":	"Spēlētāja sesija nav derīga",
					"TXT_ERROR_ACCOUNT_BLOCKED":	"Spēlētāja konts bloķēts",
					"TXT_ERROR_WAGER_FAILED":       DEFAULT_TXT_ERROR_WAGER_FAILED
			},

		"nl_nl": {
					"reality_check_title": 		"Waarschuwing",
					"reality_check_text": 		"U hebben geweest spelen %1 minuten! Druk op DOORGAAN om te blijven spelen",
					"reality_check_proceed":	"Doorgaan",
					"reality_check_exit":		"Avslutt",
					"reality_check_history":	"Accountgeschiedenis",
					
					
					"MESSAGE_BTN_NO":			"Nee",
					"MESSAGE_BTN_YES": 			"Ja",
					"MESSAGE_BTN_CANCEL": 		"Annuleren",
					"MESSAGE_BTN_SUBMIT": 		"Verzenden",
					"MESSAGE_BTN_OK": 			"OK",
					
					"MESSAGE_TITLE_PLAY_SLOT": "Speelautomaat spelen",
                    "MESSAGE_TEXT_PLAY_SLOT":  "Weet je zeker dat je de speelautomaat wilt spelen?",
					
					"MESSAGE_FULL_SCREEN":		"Volledig scherm?",

					"TXT_WARNING":					"Waarschuwing",
					"TXT_ERROR":					"Fout",
					"TXT_ERROR_PROTOCOL":			"Onbekend protocolbericht",
					"TXT_ERROR_PROTOCOL_SEQUENCE":	"Onjuiste berichtenvolgorde",
					"TXT_ERROR_UNKNOWN_PARAMETER":	"Onbekende parameter in protocol",
					"TXT_ERROR_MISSING_PARAMETER":	"Ontbrekende parameter in protocol",
					"TXT_ERROR_PARAMETER_VALUE":	"Onjuiste parameterwaarde",
					"TXT_ERROR_BET_LIMITS":			"Ingezet bedrag overschrijdt de limiet",
					"TXT_ERROR_LINES":				"Onjuist aantal lijnen",
					"TXT_ERROR_FEATURE_PARAMETERS":	"Functieparameters onjuist",
					"TXT_ERROR_JACKPOT":			"Onbekende jackpotfout",
					"TXT_ERROR_UNKNOWN":			"Onbekende fout",
					"TXT_ERROR_NULL":				"Geen communicatie met server",
					"TXT_ERROR_INSUFFICIENTFUNDS":	"Onvoldoende saldo voor de inzet",
					"TXT_ERROR_STATESAVE":			"Fout tijdens het opslaan van de status",
					"TXT_ERROR_STARTGAME":			"Fout tijdens het starten van het spel",
					"TXT_ERROR_ENDGAME":			"Fout tijdens het beëindigen van het spel",
					"TXT_ERROR_GAMENOTSUPPORTED":	"Spel wordt niet door het systeem ondersteund",
					"TXT_ERROR_TIMEOUT":			"Je bent niet meer verbonden met de server. Start het spel opnieuw.",
					"TXT_SERVLET_ERROR":			"Geen communicatie met server",
					"TXT_ERROR_DEFAULT":			"Geen communicatie met server",
					"TXT_ERROR_GAMING_LIMITS":		"Spellimieten bereikt",
					"TXT_ERROR_INVALID_SESSION":	"Spelersessie is niet geldig",
					"TXT_ERROR_ACCOUNT_BLOCKED":	"Speleraccount geblokkeerd",
					"TXT_ERROR_WAGER_FAILED":       DEFAULT_TXT_ERROR_WAGER_FAILED
			},

		"no_no": {
					"reality_check_title": 		"Virkelighetskontroll",
					"reality_check_text": 		"Du har spilt i %1 minutter! Trykk FORTSETT for å fortsette spillingen",
					"reality_check_proceed":	"Fortsett",
					"reality_check_exit":		"Avslutt",
					"reality_check_history":	"Kontohistorikk",
					
					
					"MESSAGE_BTN_NO":			"Nei",
					"MESSAGE_BTN_YES": 			"Ja",
					"MESSAGE_BTN_CANCEL": 		"Avbryt",
					"MESSAGE_BTN_SUBMIT": 		"Send",
					"MESSAGE_BTN_OK": 			"OK",
					
					"MESSAGE_TITLE_PLAY_SLOT": "Spille automaten",
                    "MESSAGE_TEXT_PLAY_SLOT":  "Er du sikker på at du vil spille automatspillet?",
					
					"MESSAGE_FULL_SCREEN":		"Fullskjerm?",

					"TXT_WARNING":					"Advarsel",
					"TXT_ERROR":					"Feil",
					"TXT_ERROR_PROTOCOL":			"Ukjent protokollmelding",
					"TXT_ERROR_PROTOCOL_SEQUENCE":	"Feil meldingssekvens",
					"TXT_ERROR_UNKNOWN_PARAMETER":	"Ukjent parameter i protokoll",
					"TXT_ERROR_MISSING_PARAMETER":	"Parameter mangler i protokoll",
					"TXT_ERROR_PARAMETER_VALUE":	"Parameterverdier er feil",
					"TXT_ERROR_BET_LIMITS":			"Innsatsbeløpet er utenfor grensen",
					"TXT_ERROR_LINES":				"Feil antall linjer",
					"TXT_ERROR_FEATURE_PARAMETERS":	"Parameterfunksjoner er feil",
					"TXT_ERROR_JACKPOT":			"Ukjent jackpot-feil",
					"TXT_ERROR_UNKNOWN":			"Ukjent feil",
					"TXT_ERROR_NULL":				"Serverkommunikasjonen mistet",
					"TXT_ERROR_INSUFFICIENTFUNDS":	"Ikke nok på saldoen til innsatsen",
					"TXT_ERROR_STATESAVE":			"Feil, prøver å lagre tilstanden",
					"TXT_ERROR_STARTGAME":			"Feil, prøver å starte spillet",
					"TXT_ERROR_ENDGAME":			"Feil, prøver å avslutte spillet",
					"TXT_ERROR_GAMENOTSUPPORTED":	"Spillet støttes ikke av systemet",
					"TXT_ERROR_TIMEOUT":			"Du er koblet fra serveren. Vennligst start spillet på nytt.",
					"TXT_SERVLET_ERROR":			"Serverkommunikasjonen mistet",
					"TXT_ERROR_DEFAULT":			"Serverkommunikasjonen mistet",
					"TXT_ERROR_GAMING_LIMITS":		"Spillegrensen er nådd",
					"TXT_ERROR_INVALID_SESSION":	"Spillerøkten er ikke gyldig",
					"TXT_ERROR_ACCOUNT_BLOCKED":	"Spillekontoen er låst",
					"TXT_ERROR_WAGER_FAILED":       DEFAULT_TXT_ERROR_WAGER_FAILED
			},

		"pl_pl": {
					"reality_check_title": 		"Kontrola czasu gry",
					"reality_check_text": 		"Ty mieć być gra %1 minut! Kliknij przycisk KONTYNUUJ, aby kontynuować grę",
					"reality_check_proceed":	"Kontynuuj",
					"reality_check_exit":		"Zakończ",
					"reality_check_history":	"Historia konta",
					
					
					"MESSAGE_BTN_NO":			"Nie",
					"MESSAGE_BTN_YES": 			"Tak",
					"MESSAGE_BTN_CANCEL": 		"Anuluj",
					"MESSAGE_BTN_SUBMIT": 		"Wyślij",
					"MESSAGE_BTN_OK": 			"OK",
					
					"MESSAGE_TITLE_PLAY_SLOT": "Chcesz zagrać",
                    "MESSAGE_TEXT_PLAY_SLOT":  "Czy chcesz rozegrać grę automatową?",
					
					"MESSAGE_FULL_SCREEN":		"Pełny ekran?",

					"TXT_WARNING":					"Ostrzeżenie",
					"TXT_ERROR":					"Błąd",
					"TXT_ERROR_PROTOCOL":			"Komunikat o nieznanym protokole",
					"TXT_ERROR_PROTOCOL_SEQUENCE":	"Nieprawidłowa kolejność komunikatów",
					"TXT_ERROR_UNKNOWN_PARAMETER":	"Nieznany parametr w protokole",
					"TXT_ERROR_MISSING_PARAMETER":	"Brakujący parametr w protokole",
					"TXT_ERROR_PARAMETER_VALUE":	"Nieprawidłowa wartość parametru",
					"TXT_ERROR_BET_LIMITS":			"Kwota zakładu przekracza limit",
					"TXT_ERROR_LINES":				"Nieprawidłowa liczba linii",
					"TXT_ERROR_FEATURE_PARAMETERS":	"Nieprawidłowe parametry funkcji",
					"TXT_ERROR_JACKPOT":			"Nieznany błąd puli",
					"TXT_ERROR_UNKNOWN":			"Nieznany błąd",
					"TXT_ERROR_NULL":				"Połączenie z serwerem zostało przerwane",
					"TXT_ERROR_INSUFFICIENTFUNDS":	"Niewystarczający bilans, aby wnieść zakład",
					"TXT_ERROR_STATESAVE":			"Błąd podczas próby zapisania stanu",
					"TXT_ERROR_STARTGAME":			"Błąd podczas próby uruchomienia gry",
					"TXT_ERROR_ENDGAME":			"Błąd podczas próby zakończenia gry",
					"TXT_ERROR_GAMENOTSUPPORTED":	"System nie obsługuje tej gry",
					"TXT_ERROR_TIMEOUT":			"Odłączono od serwera.  Ponownie uruchom grę.",
					"TXT_SERVLET_ERROR":			"Połączenie z serwerem zostało przerwane",
					"TXT_ERROR_DEFAULT":			"Połączenie z serwerem zostało przerwane",
					"TXT_ERROR_GAMING_LIMITS":		"Limity gier osiągnięte",
					"TXT_ERROR_INVALID_SESSION":	"Nieprawidłowa sesja gracza",
					"TXT_ERROR_ACCOUNT_BLOCKED":	"Konto gracza zablokowane",
					"TXT_ERROR_WAGER_FAILED":       DEFAULT_TXT_ERROR_WAGER_FAILED
			},

		"pt_pt": {
					"reality_check_title": 		"Pés na terra",
					"reality_check_text": 		"Você ter fui jogando %1 minutos! Pressione CONTINUAR para continuar a jogar",
					"reality_check_proceed":	"Continuar",
					"reality_check_exit":		"Sair",
					"reality_check_history":	"Histórico de Conta",
					
					
					"MESSAGE_BTN_NO":			"Não",
					"MESSAGE_BTN_YES": 			"Sim",
					"MESSAGE_BTN_CANCEL": 		"Cancelar",
					"MESSAGE_BTN_SUBMIT": 		"Enviar",
					"MESSAGE_BTN_OK": 			"OK",
					
					"MESSAGE_TITLE_PLAY_SLOT": "Jogar Slot",
                    "MESSAGE_TEXT_PLAY_SLOT":  "Tem a certeza de que pretende sair do jogo de slot machine?",
					
					"MESSAGE_FULL_SCREEN":		"Ecrã inteiro?",

					"TXT_WARNING":					"Aviso",
					"TXT_ERROR":					"Erro",
					"TXT_ERROR_PROTOCOL":			"Mensagem de protocolo desconhecida",
					"TXT_ERROR_PROTOCOL_SEQUENCE":	"Sequência incorreta de mensagens",
					"TXT_ERROR_UNKNOWN_PARAMETER":	"Parâmetro desconhecido no protocolo",
					"TXT_ERROR_MISSING_PARAMETER":	"Parâmetro ausente no protocolo",
					"TXT_ERROR_PARAMETER_VALUE":	"Valores de parâmetro incorretos",
					"TXT_ERROR_BET_LIMITS":			"O montante da aposta não se encontra entre os limites",
					"TXT_ERROR_LINES":				"Número de linhas incorreto",
					"TXT_ERROR_FEATURE_PARAMETERS":	"Parâmetros de opção incorretos",
					"TXT_ERROR_JACKPOT":			"Erro de jackpot desconhecido",
					"TXT_ERROR_UNKNOWN":			"Erro desconhecido",
					"TXT_ERROR_NULL":				"Perda de ligação ao servidor",
					"TXT_ERROR_INSUFFICIENTFUNDS":	"Não possui saldo suficiente para efetuar a aposta",
					"TXT_ERROR_STATESAVE":			"Erro ao tentar guardar o estado",
					"TXT_ERROR_STARTGAME":			"Erro ao tentar iniciar o jogo",
					"TXT_ERROR_ENDGAME":			"Erro ao tentar terminar o jogo",
					"TXT_ERROR_GAMENOTSUPPORTED":	"O sistema não suporta este jogo",
					"TXT_ERROR_TIMEOUT":			"Perdeu a ligação ao servidor. Por favor reinicie o jogo.",
					"TXT_SERVLET_ERROR":			"Perda de ligação ao servidor",
					"TXT_ERROR_DEFAULT":			"Perda de ligação ao servidor",
					"TXT_ERROR_GAMING_LIMITS":		"Limites alcançados",
					"TXT_ERROR_INVALID_SESSION":	"A sessão do utilizador não é válida",
					"TXT_ERROR_ACCOUNT_BLOCKED":	"Esta conta encontra-se bloqueada",
					"TXT_ERROR_WAGER_FAILED":       DEFAULT_TXT_ERROR_WAGER_FAILED
			},

		"ro_ro": {
					"reality_check_title": 		"Înapoi la realitate",
					"reality_check_text": 		"Tu avea fost joc %1 minute! Apăsați CONTINUARE pentru a rămâne în joc",
					"reality_check_proceed":	"Continuare",
					"reality_check_exit":		"Ieşire",
					"reality_check_history":	"Istoric cont",
					
					
					"MESSAGE_BTN_NO":			"Nu",
					"MESSAGE_BTN_YES": 			"Da",
					"MESSAGE_BTN_CANCEL": 		"Anulare",
					"MESSAGE_BTN_SUBMIT": 		"Înregistrare",
					"MESSAGE_BTN_OK": 			"OK",
					
					"MESSAGE_TITLE_PLAY_SLOT": "Jucați la sloturis",
                    "MESSAGE_TEXT_PLAY_SLOT":  "Sunteţi sigur/ă că doriţi să jucaţi jocul de sloturi?",
					
					"MESSAGE_FULL_SCREEN":		"Ecran complet?",

					"TXT_WARNING":					"Avertisment",
					"TXT_ERROR":					"Eroare",
					"TXT_ERROR_PROTOCOL":			"Mesaj de protocol necunoscut",
					"TXT_ERROR_PROTOCOL_SEQUENCE":	"Secvență incorectă de mesaje",
					"TXT_ERROR_UNKNOWN_PARAMETER":	"Parametru necunoscut în cadrul protocolului",
					"TXT_ERROR_MISSING_PARAMETER":	"Parametru lipsă în cadrul protocolului",
					"TXT_ERROR_PARAMETER_VALUE":	"Valoarea parametrului este greșită",
					"TXT_ERROR_BET_LIMITS":			"Valoarea pariului în afara limitelor",
					"TXT_ERROR_LINES":				"Număr incorect de linii",
					"TXT_ERROR_FEATURE_PARAMETERS":	"Parametrii secvenței incorecți",
					"TXT_ERROR_JACKPOT":			"Eroare Jackpot necunoscută",
					"TXT_ERROR_UNKNOWN":			"Eroare necunoscută",
					"TXT_ERROR_NULL":				"Comunicare cu serverul pierdută",
					"TXT_ERROR_INSUFFICIENTFUNDS":	"Soldul nu este suficient pentru Pariu",
					"TXT_ERROR_STATESAVE":			"Eroare la încercarea de a salva starea",
					"TXT_ERROR_STARTGAME":			"Eroare la încercarea de a începe jocul",
					"TXT_ERROR_ENDGAME":			"Eroare la încercarea de a termina jocul",
					"TXT_ERROR_GAMENOTSUPPORTED":	"Jocul nu este acceptat de către sistem",
					"TXT_ERROR_TIMEOUT":			"Ați fost deconectat de la server.  Reporniți jocul",
					"TXT_SERVLET_ERROR":			"Comunicare cu serverul pierdută",
					"TXT_ERROR_DEFAULT":			"Comunicare cu serverul pierdută",
					"TXT_ERROR_GAMING_LIMITS":		"Limitele de joc au ajuns la",
					"TXT_ERROR_INVALID_SESSION":	"Sesiunea jucătorului nu este valabilă",
					"TXT_ERROR_ACCOUNT_BLOCKED":	"Contul jucătorului este blocat",
					"TXT_ERROR_WAGER_FAILED":       DEFAULT_TXT_ERROR_WAGER_FAILED
			},

		"ru_ru": {
					"reality_check_title": 		"Проверка связи с реальностью",
					"reality_check_text": 		"Вы иметь было играя %1 минут! Щелкните по ПРОДОЛЖИТЬ, чтобы продолжить играть",
					"reality_check_proceed":	"Продолжить",
					"reality_check_exit":		"Выйти",
					"reality_check_history":	"История счета",
					
					
					"MESSAGE_BTN_NO":			"Нет",
					"MESSAGE_BTN_YES": 			"Да",
					"MESSAGE_BTN_CANCEL": 		"Отменить",
					"MESSAGE_BTN_SUBMIT": 		"Отправить",
					"MESSAGE_BTN_OK": 			"OK",
					
					"MESSAGE_TITLE_PLAY_SLOT": "Играть на слот-автомате",
                    "MESSAGE_TEXT_PLAY_SLOT":  "Вы уверены, что хотите сыграть на слот-автомате?",
					
					"MESSAGE_FULL_SCREEN":		"Полноэкранный режим?",

					"TXT_WARNING":					"Предупреждение",
					"TXT_ERROR":					"Ошибка",
					"TXT_ERROR_PROTOCOL":			"Неизвестное сообщение протокола",
					"TXT_ERROR_PROTOCOL_SEQUENCE":	"Неправильная последовательность сообщений",
					"TXT_ERROR_UNKNOWN_PARAMETER":	"Неизвестный параметр протокола",
					"TXT_ERROR_MISSING_PARAMETER":	"Отсутствует параметр протокола",
					"TXT_ERROR_PARAMETER_VALUE":	"Неправильное значение параметра",
					"TXT_ERROR_BET_LIMITS":			"Сумма ставки выходит за пределы допустимых значений",
					"TXT_ERROR_LINES":				"Неправильное число линий",
					"TXT_ERROR_FEATURE_PARAMETERS":	"Неправильные параметры функции",
					"TXT_ERROR_JACKPOT":			"Неизвестная ошибка джекпота",
					"TXT_ERROR_UNKNOWN":			"Неизвестная ошибка",
					"TXT_ERROR_NULL":				"Потеря связи с сервером",
					"TXT_ERROR_INSUFFICIENTFUNDS":	"Недостаточный остаток для ставки",
					"TXT_ERROR_STATESAVE":			"Ошибка при попытке сохранить состояние",
					"TXT_ERROR_STARTGAME":			"Ошибка при попытке начать игру",
					"TXT_ERROR_ENDGAME":			"Ошибка при попытке закончить игру",
					"TXT_ERROR_GAMENOTSUPPORTED":	"Игра не поддерживается системой",
					"TXT_ERROR_TIMEOUT":			"Вы отключены от сервера. Пожалуйста, перезапустите игру",
					"TXT_SERVLET_ERROR":			"Потеря связи с сервером",
					"TXT_ERROR_DEFAULT":			"Потеря связи с сервером",
					"TXT_ERROR_GAMING_LIMITS":		"Достигнуты лимиты игры",
					"TXT_ERROR_INVALID_SESSION":	"Сеанс игрока недействителен",
					"TXT_ERROR_ACCOUNT_BLOCKED":	"Аккаунт игрока заблокирован",
					"TXT_ERROR_WAGER_FAILED":       DEFAULT_TXT_ERROR_WAGER_FAILED
			},

		"sk_sk": {
					"reality_check_title": 		"Kontrola reality",
					"reality_check_text": 		"Vy mať Bol hracie %1 minúty! Stlačením tlačidla POKRAČOVAŤ pokračujte v hraní",
					"reality_check_proceed":	"Pokračovať",
					"reality_check_exit":		"Odísť",
					"reality_check_history":	"História konta",
					
					
					"MESSAGE_BTN_NO":			"Nie",
					"MESSAGE_BTN_YES": 			"Áno",
					"MESSAGE_BTN_CANCEL": 		"Zrušiť",
					"MESSAGE_BTN_SUBMIT": 		"Odoslať",
					"MESSAGE_BTN_OK": 			"OK",
					
					"MESSAGE_TITLE_PLAY_SLOT": "Hrať automatovú hru",
                    "MESSAGE_TEXT_PLAY_SLOT":  "Naozaj chcete hrať automatovú hru?",
					
					"MESSAGE_FULL_SCREEN":		"Na celú obrazovku?",

					"TXT_WARNING":					"Upozornenie",
					"TXT_ERROR":					"Chyba",
					"TXT_ERROR_PROTOCOL":			"Neznáma správa protokolu",
					"TXT_ERROR_PROTOCOL_SEQUENCE":	"Nesprávna postupnosť správ",
					"TXT_ERROR_UNKNOWN_PARAMETER":	"Neznámy parameter v protokole",
					"TXT_ERROR_MISSING_PARAMETER":	"Chýbajúci parameter v protokole",
					"TXT_ERROR_PARAMETER_VALUE":	"Nesprávna hodnota parametra",
					"TXT_ERROR_BET_LIMITS":			"Výška stávky mimo limitov",
					"TXT_ERROR_LINES":				"Nesprávny počet riadkov",
					"TXT_ERROR_FEATURE_PARAMETERS":	"Nesprávne parametre funkcie",
					"TXT_ERROR_JACKPOT":			"Neznáma chyba jackpotu",
					"TXT_ERROR_UNKNOWN":			"Neznáma chyba",
					"TXT_ERROR_NULL":				"Prerušená komunikácia so serverom",
					"TXT_ERROR_INSUFFICIENTFUNDS":	"Nedostatočný zostatok pre stávku",
					"TXT_ERROR_STATESAVE":			"Chyba pri pokuse uložiť stav",
					"TXT_ERROR_STARTGAME":			"Chyba pri pokuse spustiť hru",
					"TXT_ERROR_ENDGAME":			"Chyba pri pokuse ukončiť hru",
					"TXT_ERROR_GAMENOTSUPPORTED":	"Systém nepodporuje túto hru",
					"TXT_ERROR_TIMEOUT":			"Boli ste odpojení od servera.  Reštartujte hru",
					"TXT_SERVLET_ERROR":			"Prerušená komunikácia so serverom",
					"TXT_ERROR_DEFAULT":			"Prerušená komunikácia so serverom",
					"TXT_ERROR_GAMING_LIMITS":		"Dosiahnuté limity hry",
					"TXT_ERROR_INVALID_SESSION":	"Relácia hráča nie je platná",
					"TXT_ERROR_ACCOUNT_BLOCKED":	"Konto hráča je zablokované",
					"TXT_ERROR_WAGER_FAILED":       DEFAULT_TXT_ERROR_WAGER_FAILED
			},

		"sv_se": {
					"reality_check_title": 		"Verklighetskontroll",
					"reality_check_text": 		"Du har varit spelar %1 minut! Tryck på FORTSÄTT för att fortsätta spela",
					"reality_check_proceed":	"Fortsätt",
					"reality_check_exit":		"Avsluta",
					"reality_check_history":	"Kontohistorik",
					
					
					"MESSAGE_BTN_NO":			"Nej",
					"MESSAGE_BTN_YES": 			"Ja",
					"MESSAGE_BTN_CANCEL": 		"Avbryt",
					"MESSAGE_BTN_SUBMIT": 		"Lämna",
					"MESSAGE_BTN_OK": 			"OK",
					
					"MESSAGE_TITLE_PLAY_SLOT": "Spela spelautomat",
                    "MESSAGE_TEXT_PLAY_SLOT":  "Är du säker på att du vill spela spelautomaten?",
					
					"MESSAGE_FULL_SCREEN":		"Helskärm?",

					"TXT_WARNING":					"Varning",
					"TXT_ERROR":					"Fel",
					"TXT_ERROR_PROTOCOL":			"Okänt protokollmeddelande",
					"TXT_ERROR_PROTOCOL_SEQUENCE":	"Felaktig meddelandeordning",
					"TXT_ERROR_UNKNOWN_PARAMETER":	"Okänd parameter i protokollet",
					"TXT_ERROR_MISSING_PARAMETER":	"Saknad parameter i protokollet",
					"TXT_ERROR_PARAMETER_VALUE":	"Felaktiga parametervärden",
					"TXT_ERROR_BET_LIMITS":			"Insatsbeloppet överstiger gränsen",
					"TXT_ERROR_LINES":				"Felaktigt antal linjer",
					"TXT_ERROR_FEATURE_PARAMETERS":	"Felaktiga funktionsparametrar",
					"TXT_ERROR_JACKPOT":			"Okänt Jackpot-fel",
					"TXT_ERROR_UNKNOWN":			"Okänt fel",
					"TXT_ERROR_NULL":				"Ingen kommunikation med servern",
					"TXT_ERROR_INSUFFICIENTFUNDS":	"Otillräckligt saldo för insatsen",
					"TXT_ERROR_STATESAVE":			"Gick inte att spara status",
					"TXT_ERROR_STARTGAME":			"Gick inte att starta spelet",
					"TXT_ERROR_ENDGAME":			"Gick inte att avsluta spelet",
					"TXT_ERROR_GAMENOTSUPPORTED":	"Spelet stöds inte av systemet",
					"TXT_ERROR_TIMEOUT":			"Du har kopplats bort från servern. Vänligen starta om spelet",
					"TXT_SERVLET_ERROR":			"Ingen kommunikation med servern",
					"TXT_ERROR_DEFAULT":			"Ingen kommunikation med servern",
					"TXT_ERROR_GAMING_LIMITS":		"Spelgränsen är uppnådd",
					"TXT_ERROR_INVALID_SESSION":	"Spelarsessionen är inte giltig",
					"TXT_ERROR_ACCOUNT_BLOCKED":	"Spelarens konto är låst",
					"TXT_ERROR_WAGER_FAILED":       DEFAULT_TXT_ERROR_WAGER_FAILED
			},

			
		"th_th": {
					"reality_check_title": 		"ตรวจสอบความเป็นจริง",
					"reality_check_text": 		"ท่านได้เล่นมาเป็นเวลา %1 นาทีแล้ว กดที่ เล่นต่อ เพื่อทำการเล่นต่อ",
					"reality_check_proceed":	"เล่นต่อ",
					"reality_check_exit":		"ออก",
					"reality_check_history":	"ประวัติบัญชี",
					
					
					"MESSAGE_BTN_NO":			"ไม่",
					"MESSAGE_BTN_YES": 			"ใช่",
					"MESSAGE_BTN_CANCEL": 		"ยกเลิก",
					"MESSAGE_BTN_SUBMIT": 		"ส่ง",
					"MESSAGE_BTN_OK": 			"ตกลง",
					
					
					"MESSAGE_TITLE_PLAY_SLOT": "เล่นเกมตู้สล็อต",
                    "MESSAGE_TEXT_PLAY_SLOT":  "ท่านแน่ใจหรือว่าต้องการเล่นเกมตู้สล็อต",
					
					"MESSAGE_FULL_SCREEN":		"เต็มหน้าจอ?",

					"TXT_WARNING":					"คำเตือน",
					"TXT_ERROR":					"ข้อผิดพลาด",
					"TXT_ERROR_PROTOCOL":			"ข้อความโปรโตคอลที่ไม่ทราบ",
					"TXT_ERROR_PROTOCOL_SEQUENCE":	"ลำดับข้อความไม่ถูกต้อง",
					"TXT_ERROR_UNKNOWN_PARAMETER":	"มีพารามิเตอร์ที่ไม่รู้จักในโปรโตคอล",
					"TXT_ERROR_MISSING_PARAMETER":	"พารามิเตอร์หายไปจากในโปรโตคอล",
					"TXT_ERROR_PARAMETER_VALUE":	"ค่าพารามิเตอร์ผิด",
					"TXT_ERROR_BET_LIMITS":			"จำนวนเงินลงเดิมพันเกินขอบเขต",
					"TXT_ERROR_LINES":				"จำนวนไลน์ไม่ถูกต้อง",
					"TXT_ERROR_FEATURE_PARAMETERS":	"พารามิเตอร์ของฟีเจอร์ไม่ถูกต้อง",
					"TXT_ERROR_JACKPOT":			"เกิดข้อผิดพลาดกับแจ๊คพ็อตที่ไม่ทราบสาเหตุ",
					"TXT_ERROR_UNKNOWN":			"ข้อผิดพลาดที่ไม่ทราบสาเหตุ",
					"TXT_ERROR_NULL":				"การสื่อสารกับเซิร์ฟเวอร์ขาดหาย",
					"TXT_ERROR_INSUFFICIENTFUNDS":	"ยอดเงินคงเหลือไม่เพียงพอสำหรับลงเดิมพัน",
					"TXT_ERROR_STATESAVE":			"เกิดข้อผิดพลาดในการบันทึกสถานะ",
					"TXT_ERROR_STARTGAME":			"เกิดข้อผิดพลาดในการเริ่มเกม",
					"TXT_ERROR_ENDGAME":			"เกิดข้อผิดพลาดในการจบเกม",
					"TXT_ERROR_GAMENOTSUPPORTED":	"เกมไม่ได้รับการรองรับจากระบบ",
					"TXT_ERROR_TIMEOUT":			"ท่านถูกตัดการเชื่อมต่อกับเซิร์ฟเวอร์  กรุณาเริ่มเกมใหม่",
					"TXT_SERVLET_ERROR":			"การสื่อสารกับเซิร์ฟเวอร์ขาดหาย",
					"TXT_ERROR_DEFAULT":			"การสื่อสารกับเซิร์ฟเวอร์ขาดหาย",
					"TXT_ERROR_GAMING_LIMITS":		"ถึงขีดจำกัดการการเล่นเกม!",
					"TXT_ERROR_INVALID_SESSION":	"ช่วงเซสชั่นของผู้เล่นไม่ถูกต้อง",
					"TXT_ERROR_ACCOUNT_BLOCKED":	"บัญขีของผู้เล่นถูกล็อค",
					"TXT_ERROR_WAGER_FAILED":       DEFAULT_TXT_ERROR_WAGER_FAILED
			},
				
		"tr_tr": {
					"reality_check_title": 		"Gerçek Kişi Kontrolü",
					"reality_check_text": 		"Sen var olmuştur oynama %1 dakika! Oynamaya devam etmek için DEVAM'a basın",
					"reality_check_proceed":	"Devam",
					"reality_check_exit":		"Çikiş",
					"reality_check_history":	"Hesap Geçmişi",
					
					
					"MESSAGE_BTN_NO":			"Hayır",
					"MESSAGE_BTN_YES": 			"Evet",
					"MESSAGE_BTN_CANCEL": 		"İptal",
					"MESSAGE_BTN_SUBMIT": 		"Gönder",
					"MESSAGE_BTN_OK": 			"TAMAM",
					
					"MESSAGE_TITLE_PLAY_SLOT": "Slot Oynar Mısın",
                    "MESSAGE_TEXT_PLAY_SLOT":  "Slot oyununu oynamak istediğinizden emin misiniz?",
					
					"MESSAGE_FULL_SCREEN":		"Tam Ekran?",

					"TXT_WARNING":					"Uyarı",
					"TXT_ERROR":					"Hata",
					"TXT_ERROR_PROTOCOL":			"Bilinmeyen protokol iletisi",
					"TXT_ERROR_PROTOCOL_SEQUENCE":	"Yanlış İleti Sırası",
					"TXT_ERROR_UNKNOWN_PARAMETER":	"Protokolde bilinmeyen parametre",
					"TXT_ERROR_MISSING_PARAMETER":	"Protokolde eksik parametre",
					"TXT_ERROR_PARAMETER_VALUE":	"Parametre Değerleri yanlış",
					"TXT_ERROR_BET_LIMITS":			"Limitlerin dışında bir miktarda bahis",
					"TXT_ERROR_LINES":				"Yanlış hat sayısı",
					"TXT_ERROR_FEATURE_PARAMETERS":	"Özellik Parametreleri yanlış",
					"TXT_ERROR_JACKPOT":			"Bilinmeyen Jackpot hatası",
					"TXT_ERROR_UNKNOWN":			"Bilinmeyen hata",
					"TXT_ERROR_NULL":				"Sunucuyla iletişim kesildi",
					"TXT_ERROR_INSUFFICIENTFUNDS":	"Bahis için yeterli bakiye yok",
					"TXT_ERROR_STATESAVE":			"Durumu kaydetme sırasında hata oluştu",
					"TXT_ERROR_STARTGAME":			"Oyunu başlatma sırasında hata oluştu",
					"TXT_ERROR_ENDGAME":			"Oyunu sonlandırma sırasında hata oluştu",
					"TXT_ERROR_GAMENOTSUPPORTED":	"Oyun sistem tarafından desteklenmiyor",
					"TXT_ERROR_TIMEOUT":			"Sunucuyla bağlantınız kesildi.  Lütfen oyunu yeniden başlatın.",
					"TXT_SERVLET_ERROR":			"Sunucuyla iletişim kesildi",
					"TXT_ERROR_DEFAULT":			"Sunucuyla iletişim kesildi",
					"TXT_ERROR_GAMING_LIMITS":		"Oyun limitlerine ulaşıldı",
					"TXT_ERROR_INVALID_SESSION":	"Oyuncu oturumu geçerli değil",
					"TXT_ERROR_ACCOUNT_BLOCKED":	"Oyuncu hesabı kilitlendi",
					"TXT_ERROR_WAGER_FAILED":       DEFAULT_TXT_ERROR_WAGER_FAILED
			},

		"zh_cn": {
					"reality_check_title": 		"自我反思",
					"reality_check_text": 		"您 有 一直 播放%1分钟！按“继续”以继续玩游戏",
					"reality_check_proceed":	"继续",
					"reality_check_exit":		"退出",
					"reality_check_history":	"帐户历史记录",
					
					
					"MESSAGE_BTN_NO":			"否",
					"MESSAGE_BTN_YES": 			"是",
					"MESSAGE_BTN_CANCEL": 		"取消",
					"MESSAGE_BTN_SUBMIT": 		"提交",
					"MESSAGE_BTN_OK": 			"确定",
					
					"MESSAGE_TITLE_PLAY_SLOT": "玩老虎机",
                    "MESSAGE_TEXT_PLAY_SLOT":  "您确定要玩老虎机游戏吗？",
					
					"MESSAGE_FULL_SCREEN":		"全屏？",

					"TXT_WARNING":					"警告",
					"TXT_ERROR":					"错误",
					"TXT_ERROR_PROTOCOL":			"未知协议消息",
					"TXT_ERROR_PROTOCOL_SEQUENCE":	"不正确的消息顺序",
					"TXT_ERROR_UNKNOWN_PARAMETER":	"协议中有未知参数",
					"TXT_ERROR_MISSING_PARAMETER":	"协议中丢失参数",
					"TXT_ERROR_PARAMETER_VALUE":	"参数值错误",
					"TXT_ERROR_BET_LIMITS":			"下注金额超出限制",
					"TXT_ERROR_LINES":				"中奖线数目不正确",
					"TXT_ERROR_FEATURE_PARAMETERS":	"功能参数不正确",
					"TXT_ERROR_JACKPOT":			"未知的累积奖金错误",
					"TXT_ERROR_UNKNOWN":			"未知错误",
					"TXT_ERROR_NULL":				"服务器通讯中断",
					"TXT_ERROR_INSUFFICIENTFUNDS":	"没有足够的余额下注",
					"TXT_ERROR_STATESAVE":			"尝试保存状态时出错",
					"TXT_ERROR_STARTGAME":			"尝试开始游戏时出错",
					"TXT_ERROR_ENDGAME":			"尝试结束游戏时出错",
					"TXT_ERROR_GAMENOTSUPPORTED":	"系统不支持游戏",
					"TXT_ERROR_TIMEOUT":			"您已从服务器断开。  请重新启动游戏。",
					"TXT_SERVLET_ERROR":			"服务器通讯中断",
					"TXT_ERROR_DEFAULT":			"服务器通讯中断",
					"TXT_ERROR_GAMING_LIMITS":		"已达到游戏次数上限",
					"TXT_ERROR_INVALID_SESSION":	"玩家会话无效",
					"TXT_ERROR_ACCOUNT_BLOCKED":	"玩家帐户已锁定",
					"TXT_ERROR_WAGER_FAILED":       DEFAULT_TXT_ERROR_WAGER_FAILED
			},

		"zh_tw": {
					"reality_check_title": 		"現況檢視",
					"reality_check_text": 		"您已一直播放 %1 分鐘! 請點擊 \"繼續\" 來繼續遊戲",
					"reality_check_proceed":	"繼續",
					"reality_check_exit":		"結束",
					"reality_check_history":	"帳戶歷史資料",
					
					
					"MESSAGE_BTN_NO":			"否",
					"MESSAGE_BTN_YES": 			"是",
					"MESSAGE_BTN_CANCEL": 		"取消",
					"MESSAGE_BTN_SUBMIT": 		"提交",
					"MESSAGE_BTN_OK": 			"OK",
					
					"MESSAGE_TITLE_PLAY_SLOT": "玩老虎機",
                    "MESSAGE_TEXT_PLAY_SLOT":  "您確定要進行老虎機遊戲嗎？",
					
					"MESSAGE_FULL_SCREEN":		"全螢幕?",

					"TXT_WARNING":					"警告",
					"TXT_ERROR":					"錯誤",
					"TXT_ERROR_PROTOCOL":			"未知的通訊協定訊息",
					"TXT_ERROR_PROTOCOL_SEQUENCE":	"不正確的訊息序列",
					"TXT_ERROR_UNKNOWN_PARAMETER":	"通訊協定中包含未知參數",
					"TXT_ERROR_MISSING_PARAMETER":	"通訊協定中遺失參數",
					"TXT_ERROR_PARAMETER_VALUE":	"參數值錯誤",
					"TXT_ERROR_BET_LIMITS":			"賭注超出限制",
					"TXT_ERROR_LINES":				"不正確的贏數",
					"TXT_ERROR_FEATURE_PARAMETERS":	"功能參數不正確",
					"TXT_ERROR_JACKPOT":			"未知的累積獎金錯誤",
					"TXT_ERROR_UNKNOWN":			"未知的錯誤",
					"TXT_ERROR_NULL":				"伺服器通訊遺失",
					"TXT_ERROR_INSUFFICIENTFUNDS":	"賭注的餘額不足",
					"TXT_ERROR_STATESAVE":			"嘗試儲存狀態時發生錯誤",
					"TXT_ERROR_STARTGAME":			"嘗試開始遊戲時發生錯誤",
					"TXT_ERROR_ENDGAME":			"嘗試結束遊戲時發生錯誤",
					"TXT_ERROR_GAMENOTSUPPORTED":	"系統不支援遊戲",
					"TXT_ERROR_TIMEOUT":			"您已經從伺服器斷開。請重新開始遊戲。",
					"TXT_SERVLET_ERROR":			"伺服器通訊遺失",
					"TXT_ERROR_DEFAULT":			"伺服器通訊遺失",
					"TXT_ERROR_GAMING_LIMITS":		"達到遊戲限制",
					"TXT_ERROR_INVALID_SESSION":	"玩家會話無效",
					"TXT_ERROR_ACCOUNT_BLOCKED":	"玩家帳號鎖定",
					"TXT_ERROR_WAGER_FAILED":       DEFAULT_TXT_ERROR_WAGER_FAILED
			}
	}
};


if (typeof exports !== 'undefined') {
	module.exports = {
		wrappertexts: wrappertexts
	};
}
